using System;
using AutoMapper.Attributes;

namespace NESI.DTO.Models.Core
{
	[MapsTo(typeof(NESI.Data.Entities.woprog))]
	[MapsFrom(typeof(NESI.Data.Entities.woprog))]
	public class WoProg
	{
		public long woprog_id { get; set; }
		public long? woprog_company_id { get; set; }
		public string woprog_bvwo { get; set; }
		public string woprog_customername { get; set; }
		public DateTime? woprog_opendatetime { get; set; }
		public DateTime? woprog_closedatetime { get; set; }
		public DateTime? woprog_cutdatetime { get; set; }
		public string woprog_description { get; set; }
		public string woprog_quoteid { get; set; }
		public long? woprog_pm_memberid { get; set; }
		public string WOProg_CustPO { get; set; }
		public string WOProg_InvoiceNo { get; set; }
		public DateTime? WOProg_InvoiceDate { get; set; }
		public long? woprog_customer_id { get; set; }
		public string WOProg_Status { get; set; }
		public int? WOProg_Interbranch_WOProg_ID { get; set; }
		public string WOPRog_Uncertainty { get; set; }
		public string WOPRog_Advancement { get; set; }
		public bool? WOProg_RDFlag { get; set; }
		public bool? WOProg_ServiceCall { get; set; }
		public long? woprog_cutby_memberid { get; set; }
		public long? woprog_department { get; set; }
		public int? WOProg_Contact_ID { get; set; }
		public int? WOProg_Address_ID { get; set; }
		public string WOProg_Location_in_plant { get; set; }
		public string WOProg_SpecialInstructions { get; set; }
		public int? WOProg_ERID { get; set; }
		public decimal? WOProg_LabourTotalSell { get; set; }
		public decimal? WOProg_MaterialTotalSell { get; set; }
		public decimal WOProg_JobCost_Tracking { get; set; }
		public decimal WOProg_Billed_As_Quoted { get; set; }
		public decimal? WOProg_QuotedHoursTotal { get; set; }
		public decimal? WOProg_QuotedAmount { get; set; }
		public decimal WOProg_TimeSheet_Percentage { get; set; }
		public decimal? WOProg_InvoicedNetTotal { get; set; }
		public int? WOProg_LocalTax1 { get; set; }
		public int? WOProg_LocalTax2 { get; set; }
		public int? WOProg_LocalTax3 { get; set; }
		public decimal? WOProg_HoursSpentQuoting { get; set; }
		public decimal woprog_expected_sales_value { get; set; }
		public decimal WOProg_LaborCost { get; set; }
		public decimal WOProg_MaterialCost { get; set; }
		public long? WOProg_Associate_WOProg_ID { get; set; }
		public long? WOProg_SP_MemberID { get; set; }
		public int? woprog_quotedprice_type { get; set; }
		public long WOProg_Tax1 { get; set; }
		public long WOProg_Tax2 { get; set; }
		public long WOProg_Tax3 { get; set; }
		public long WOProg_tax4 { get; set; }
		public decimal WOProg_ProgressBilled { get; set; }
		public decimal WOProg_StillToBeBilled { get; set; }
		public decimal WOProg_TotalTAndM { get; set; }
		public decimal? woprog_grossmargin { get; set; }
		public decimal Material_Sell_Estimated { get; set; }
		public decimal Labour_Sell_Estimated { get; set; }
		public long? WOProg_Customer_Consolidation { get; set; }
		public DateTime? woprog_expected_startdate { get; set; }
		public DateTime? woprog_expected_enddate { get; set; }
		public byte WOProg_Hold { get; set; }
		public long? WOProg_MakeID { get; set; }
		public long? WOProg_ModelID { get; set; }
		public long? WOProg_ERWarranty { get; set; }
		public byte WOProg_Apply_Discount { get; set; }
		public string WOProg_CoreCompetency { get; set; }
		public string woprog_customersnotes { get; set; }
		public DateTime? woprog_ExpectedCheckRun { get; set; }
		public int? woprog_creditcard_payment { get; set; }
		public string woprog_collection_notes { get; set; }
		public DateTime? woprog_last_email_date { get; set; }
		public DateTime? woprog_last_faxed_date { get; set; }
		public DateTime? woprog_invoice_paid_date { get; set; }
		public System.DateTime woprog_ts { get; set; }
		public int woprog_dayscredit { get; set; }
		public string woprog_whyhold { get; set; }
		public int? woprog_onholdmemberid { get; set; }
		public bool? woprog_vis_to_cust { get; set; }
		public double? woprog_invoice_tax { get; set; }
		public int? woprog_invoice_collection_status { get; set; }
		public bool woprog_iscredit { get; set; }
		public bool woprog_isrebill { get; set; }
		public string woprog_whycredit { get; set; }
		public int? woprog_wocredit { get; set; }
		public decimal woprog_invoicebalance { get; set; }
		public decimal woprog_invoiceCreditAmt { get; set; }
		public string woprog_servicereportdesc { get; set; }
		public int? woprog_custpo_member_id { get; set; }
		public DateTime? woprog_custpo_dt { get; set; }
		public bool? woprog_verbal_quote { get; set; }
		public double? woprog_exp_labor { get; set; }
		public int? woprog_assetid { get; set; }
		public int? woprog_default_invoicetype { get; set; }
		public int woprog_auto_invoice { get; set; }
		public string woprog_glposting_instructions { get; set; }
		public bool? woprog_isdownpayment { get; set; }
		public int? schedule_status_id { get; set; }
		public DateTime? woprog_notification_sent { get; set; }
		public DateTime? woprog_survey_sent { get; set; }
		public int? warranty { get; set; }
		public DateTime? survey_finished { get; set; }
		public double benchmark_credit { get; set; }
		public double? benchmark_labor_sell { get; set; }
		public double? benchmark_material_sell { get; set; }
		public int? parent_woprog_id { get; set; }
		public bool? requires_quote_split { get; set; }
		public decimal? this_wo_labour_cost { get; set; }
		public decimal? this_wo_material_cost { get; set; }
		public decimal? this_wo_labour_bench { get; set; }
		public decimal? this_wo_material_bench { get; set; }
		public int? currency_id { get; set; }
		public int? approved_by_parent_member_id { get; set; }
		public string default_labour_sell_gl { get; set; }
		public string default_material_sell_gl { get; set; }
		public double lag { get; set; }
		public DateTime? max_waitingtobeinvoiced_dt { get; set; }
		public bool? inspection_required { get; set; }
		public string inspection_link { get; set; }
		public int? business_unit_id { get; set; }
	}
}