//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class adp_canada_codes
    {
        public int code { get; set; }
        public string name { get; set; }
    }
}
