//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class cellphone_app_sim
    {
        public int sim_id { get; set; }
        public string sim_serial { get; set; }
        public string phone_number { get; set; }
        public Nullable<bool> is_ne_sim { get; set; }
        public string network { get; set; }
        public string last_imei { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    }
}
