//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class cellphone_number
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cellphone_number()
        {
            this.member = new HashSet<member>();
        }
    
        public int id { get; set; }
        public string number { get; set; }
        public Nullable<int> cellphone_carrier_id { get; set; }
        public string simcard { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<System.DateTime> activedate { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public Nullable<int> business_unit_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<member> member { get; set; }
    }
}
