//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificates_credential_link
    {
        public int id { get; set; }
        public Nullable<int> certificate_id { get; set; }
        public string state_province { get; set; }
        public string credential { get; set; }
    }
}
