//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_review
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<int> reviewed_by_id { get; set; }
        public short locked { get; set; }
        public Nullable<int> mt { get; set; }
        public Nullable<int> offerid { get; set; }
        public int was_printed { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
        public Nullable<int> oldid { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
    }
}
