//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class er_branch_data
    {
        public int er_branch_data_id { get; set; }
        public Nullable<int> er_branch_data_itemid { get; set; }
        public Nullable<int> er_branch_data_companyid { get; set; }
        public Nullable<double> er_branch_data_repairprice { get; set; }
        public Nullable<double> er_branch_data_newprice { get; set; }
        public Nullable<double> er_branch_data_qtyinstock { get; set; }
        public Nullable<int> business_unit_id { get; set; }
    }
}
