//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class error
    {
        public long Error_ID { get; set; }
        public int Error_Member_ID { get; set; }
        public string Error_DSN { get; set; }
        public string Error_Desc { get; set; }
        public System.DateTime Error_DateTime { get; set; }
    }
}
