//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_table
    {
        public long id { get; set; }
        public System.DateTime dateoccured { get; set; }
        public string event_text { get; set; }
        public string member_id { get; set; }
    }
}
