//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense_seller
    {
        public int id_seller { get; set; }
        public string name_seller { get; set; }
        public Nullable<int> added_by { get; set; }
        public Nullable<System.DateTime> added_dt { get; set; }
    }
}
