//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fytarget
    {
        public int id { get; set; }
        public string target_name { get; set; }
        public Nullable<int> companyid { get; set; }
        public Nullable<int> fy { get; set; }
        public Nullable<int> budget_detailid { get; set; }
        public Nullable<double> target_value { get; set; }
        public Nullable<int> m1 { get; set; }
        public Nullable<int> m2 { get; set; }
        public Nullable<int> m3 { get; set; }
        public Nullable<int> m4 { get; set; }
        public Nullable<int> m5 { get; set; }
        public Nullable<int> m6 { get; set; }
        public Nullable<int> m7 { get; set; }
        public Nullable<int> m8 { get; set; }
        public Nullable<int> m9 { get; set; }
        public Nullable<int> m10 { get; set; }
        public Nullable<int> m11 { get; set; }
        public Nullable<int> m12 { get; set; }
        public Nullable<int> business_unit_id { get; set; }
    }
}
