//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class huddle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public huddle()
        {
            this.huddle_task = new HashSet<huddle_task>();
            this.huddle_user = new HashSet<huddle_user>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> captain { get; set; }
        public Nullable<System.DateTime> dt_created { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> date_of_huddle { get; set; }
    
        public virtual member member { get; set; }
        public virtual member member1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<huddle_task> huddle_task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<huddle_user> huddle_user { get; set; }
    }
}
