//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class inc_stmt_note
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> division_id { get; set; }
        public string fisc_end { get; set; }
        public Nullable<int> gl_acct_no { get; set; }
        public string cr_dr_desig { get; set; }
        public Nullable<int> member_id { get; set; }
        public string note { get; set; }
        public Nullable<int> business_unit_id { get; set; }
        public Nullable<int> tax_entity_id { get; set; }
    }
}
