//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_lookup
    {
        public Nullable<int> tag { get; set; }
        public int item { get; set; }
        public string attval { get; set; }
        public Nullable<int> active { get; set; }
        public string C_pattern { get; set; }
    }
}
