//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_group_hdr
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<long> member_id { get; set; }
        public Nullable<System.DateTime> created_dt { get; set; }
        public System.DateTime edited_dt { get; set; }
        public string Notes { get; set; }
    }
}
