//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_annual_counts_history
    {
        public int id { get; set; }
        public Nullable<int> companyid { get; set; }
        public int masterid { get; set; }
        public Nullable<double> previous_qty { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<double> prev_dollar_balance { get; set; }
        public Nullable<double> post_dollar_balance { get; set; }
        public double qty { get; set; }
        public int locationid { get; set; }
        public Nullable<int> markerid { get; set; }
        public System.DateTime ts { get; set; }
        public int memberid { get; set; }
        public Nullable<System.DateTime> date_transferred { get; set; }
        public string origin { get; set; }
        public Nullable<double> pre_onhand_qty { get; set; }
        public Nullable<double> post_onhand_qty { get; set; }
        public int business_unit_id { get; set; }
    }
}
