//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_incorrect_levels
    {
        public int id { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> cleared_date { get; set; }
        public Nullable<int> cleared_by { get; set; }
        public Nullable<double> reported_qty { get; set; }
        public string notes { get; set; }
        public Nullable<int> master_id { get; set; }
        public Nullable<double> incorrect_qty { get; set; }
        public Nullable<double> changed_to_qty { get; set; }
    }
}
