//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_import_stage
    {
        public int inventory_import_stage_id { get; set; }
        public string external_id { get; set; }
        public Nullable<int> inventory_master_id { get; set; }
        public Nullable<int> inventory_location_master_id { get; set; }
        public Nullable<int> business_unit_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> minimum { get; set; }
        public Nullable<decimal> maximum { get; set; }
        public Nullable<decimal> unit_cost { get; set; }
        public string batch_id { get; set; }
        public bool has_validation_errors { get; set; }
        public string validation_errors { get; set; }
        public bool has_processing_error { get; set; }
        public string processing_error { get; set; }
        public bool is_processed { get; set; }
        public System.DateTime insert_ts { get; set; }
        public Nullable<int> inventory_location_id { get; set; }
    }
}
