//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_reference
    {
        public int id { get; set; }
        public string reference_part_number { get; set; }
        public string description { get; set; }
        public int master_id { get; set; }
        public Nullable<int> typereference_id { get; set; }
        public Nullable<int> referencetype_id { get; set; }
        public Nullable<int> active { get; set; }
        public string ref_vendor_number { get; set; }
        public Nullable<long> ref_member_id { get; set; }
        public Nullable<long> ref_company_id { get; set; }
        public System.DateTime updated_dt { get; set; }
        public Nullable<int> business_unit_id { get; set; }
    }
}
