//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberoffer_cr
    {
        public int memberoffer_cr_id { get; set; }
        public Nullable<int> memberoffer_crid { get; set; }
        public Nullable<int> memberoffer_moid { get; set; }
        public string cr_wording { get; set; }
        public string annually { get; set; }
        public string quarterly { get; set; }
        public string weekly { get; set; }
        public string as_required { get; set; }
        public string daily { get; set; }
        public string monthly { get; set; }
    }
}
