//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class membertime_projecttask
    {
        public int membertime_projecttask_id { get; set; }
        public int MemberTime_ID { get; set; }
        public int membertime_projecttask_netsuite_xref_id { get; set; }
        public System.DateTime update_ts { get; set; }
    
        public virtual membertime_projecttask_netsuite_xref membertime_projecttask_netsuite_xref { get; set; }
    }
}
