//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ne_session
    {
        public int id { get; set; }
        public string ip { get; set; }
        public int member_id { get; set; }
        public Nullable<bool> is_active { get; set; }
        public bool is_contact { get; set; }
        public System.DateTime dt_init { get; set; }
        public System.DateTime ts { get; set; }
        public Nullable<int> res_x { get; set; }
        public Nullable<int> res_y { get; set; }
    }
}
