//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class no_of_quotes_bypm
    {
        public int Member_ID { get; set; }
        public string Member_FirstName { get; set; }
        public string Member_LastName { get; set; }
        public long no_of_quotes { get; set; }
        public Nullable<decimal> Sum_quote_master_quoted_price_ { get; set; }
    }
}
