//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone_numbers
    {
        public int phone_numbers_id { get; set; }
        public Nullable<int> phone_numbers_table_id { get; set; }
        public string phone_numbers_type { get; set; }
        public Nullable<System.DateTime> phone_numbers_added_date { get; set; }
        public Nullable<bool> phone_numbers_active { get; set; }
        public string phone_numbers_comm_type { get; set; }
        public string phone_numbers_comments { get; set; }
        public string phone_numbers_number { get; set; }
        public Nullable<bool> phone_numbers_default { get; set; }
    }
}
