//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class quote_master
    {
        public long quote_id { get; set; }
        public int revision { get; set; }
        public Nullable<int> active_revision { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> prev_status_id { get; set; }
        public Nullable<long> customer_id { get; set; }
        public Nullable<System.DateTime> open_date { get; set; }
        public Nullable<System.DateTime> date_due { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
        public string job_description { get; set; }
        public string cust_spec_doc { get; set; }
        public Nullable<long> quoted_by { get; set; }
        public Nullable<int> quoter_locked { get; set; }
        public Nullable<int> company_id { get; set; }
        public long division_id { get; set; }
        public Nullable<long> killed_by { get; set; }
        public Nullable<int> competitor_id { get; set; }
        public Nullable<int> Contact_ID { get; set; }
        public Nullable<int> include_title { get; set; }
        public Nullable<System.DateTime> last_print_date { get; set; }
        public Nullable<System.DateTime> last_fax_date { get; set; }
        public Nullable<System.DateTime> verified_date { get; set; }
        public decimal quoted_price { get; set; }
        public Nullable<decimal> price_to { get; set; }
        public Nullable<decimal> take_off_price { get; set; }
        public string custom_term { get; set; }
        public Nullable<decimal> tm_pricing { get; set; }
        public int net_due { get; set; }
        public Nullable<int> percentage_down { get; set; }
        public Nullable<int> us_currency { get; set; }
        public Nullable<int> inflation_term { get; set; }
        public int pricetype_id { get; set; }
        public string po { get; set; }
        public Nullable<int> wo { get; set; }
        public Nullable<long> duped_from_id { get; set; }
        public Nullable<int> duped_from_rev { get; set; }
        public string updated_by_page { get; set; }
        public Nullable<int> success_percent { get; set; }
        public Nullable<byte> quote_master_apply_discount { get; set; }
        public Nullable<int> address_id { get; set; }
        public string why_lose { get; set; }
        public string who_competitor { get; set; }
        public string what_price { get; set; }
        public string cust_reason_for_close { get; set; }
        public Nullable<int> pct_chance { get; set; }
        public Nullable<int> pct_chance_reason { get; set; }
        public string pct_chance_note { get; set; }
        public double hours_spent { get; set; }
        public Nullable<bool> use_current_cost { get; set; }
        public Nullable<double> margin { get; set; }
        public Nullable<double> expected_value { get; set; }
        public Nullable<bool> follow_up { get; set; }
        public Nullable<int> allowed_to_quote { get; set; }
        public Nullable<int> allowed_to_quote_2 { get; set; }
        public string killed_at_stage { get; set; }
        public Nullable<System.DateTime> killed_date { get; set; }
        public string why_killed { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public Nullable<int> currency { get; set; }
        public string why_revised { get; set; }
        public Nullable<int> business_unit_id { get; set; }
        public Nullable<System.DateTime> exp_podate { get; set; }
        public Nullable<bool> parallel_bid { get; set; }
        public System.DateTime last_saved { get; set; }
        public Nullable<System.DateTime> date_expected_start { get; set; }
        public int revenue_line_id { get; set; }
        public Nullable<bool> is_tm { get; set; }
        public int period_valid { get; set; }
        public int opportunity_internal_id { get; set; }
        public Nullable<int> bdm { get; set; }
        public Nullable<int> acting_bdm { get; set; }
    }
}
