//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class quote_process_question_history
    {
        public int id { get; set; }
        public Nullable<int> question_id { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public Nullable<int> memberid { get; set; }
        public string notes { get; set; }
        public Nullable<int> quoteid { get; set; }
        public Nullable<int> revision { get; set; }
        public Nullable<int> @checked { get; set; }
    }
}
