//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class quote_cust_notes
    {
        public int quote_cust_notes_id { get; set; }
        public string quote_cust_notes_notes { get; set; }
        public Nullable<int> quote_cust_notes_quoteid { get; set; }
        public Nullable<System.DateTime> quote_cust_notes_ts { get; set; }
        public Nullable<int> quote_cust_notes_by { get; set; }
    }
}
