//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class rd
    {
        public int RD_ID { get; set; }
        public Nullable<int> RD_WOProgID { get; set; }
        public string RD_ProjectAdvancement { get; set; }
        public string RD_ProjectUncertainty { get; set; }
        public long RD_Member_ID { get; set; }
        public System.DateTime RD_Date_Entered { get; set; }
        public long RD_MemberTime_ID { get; set; }
    }
}
