//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class specific_notes
    {
        public int id { get; set; }
        public string notes_name { get; set; }
        public string notes { get; set; }
        public int added_by { get; set; }
        public System.DateTime created_time { get; set; }
        public int modified_by { get; set; }
        public System.DateTime modified_time { get; set; }
        public int business_unit_id { get; set; }
        public bool is_deleted { get; set; }
        public int deleted_by { get; set; }
        public int type { get; set; }
    }
}
