//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class target
    {
        public int target_ID { get; set; }
        public Nullable<int> target_CompanyID { get; set; }
        public Nullable<int> target_target_type_id { get; set; }
        public Nullable<double> target_value { get; set; }
        public Nullable<System.DateTime> target_StartDate { get; set; }
        public Nullable<System.DateTime> target_EndDate { get; set; }
        public string target_notes { get; set; }
        public Nullable<bool> target_active { get; set; }
        public Nullable<int> business_unit_id { get; set; }
    }
}
