//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax_entity_group_link
    {
        public int id { get; set; }
        public Nullable<int> tax_entity_group_id { get; set; }
        public Nullable<int> tax_entity_id { get; set; }
    
        public virtual tax_entity tax_entity { get; set; }
        public virtual tax_entity_group tax_entity_group { get; set; }
    }
}
