//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket_files
    {
        public int id { get; set; }
        public int ticket_id { get; set; }
        public string path { get; set; }
        public Nullable<int> rev { get; set; }
    }
}
