//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class training_header
    {
        public int id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public string phone_number { get; set; }
        public string contact_info { get; set; }
        public Nullable<int> quality { get; set; }
        public Nullable<bool> is_internal { get; set; }
        public string notes { get; set; }
    }
}
