//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_pogrid_onwopage
    {
        public string poprog_bvpo { get; set; }
        public int masterid { get; set; }
        public string description { get; set; }
        public decimal qty_ord { get; set; }
        public decimal qty_rec { get; set; }
        public decimal cost { get; set; }
        public decimal Extd_Cost { get; set; }
        public Nullable<System.DateTime> recd_date { get; set; }
        public Nullable<System.DateTime> placed_date { get; set; }
        public long complete { get; set; }
        public string vendorname { get; set; }
        public int wo_progid { get; set; }
        public long po_details_id { get; set; }
        public int poprogid { get; set; }
        public int vendorid { get; set; }
        public string status { get; set; }
    }
}
