//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_woprog
    {
        public long id { get; set; }
        public Nullable<int> business_unit_id { get; set; }
        public string bvwo { get; set; }
        public string customername { get; set; }
        public Nullable<System.DateTime> opendatetime { get; set; }
        public Nullable<System.DateTime> closedatetime { get; set; }
        public Nullable<System.DateTime> cutdatetime { get; set; }
        public string description { get; set; }
        public string quoteid { get; set; }
        public Nullable<long> pm_memberid { get; set; }
        public string CustPO { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<long> customer_id { get; set; }
        public string Status { get; set; }
        public Nullable<int> Interbranch_WOProg_ID { get; set; }
        public string Uncertainty { get; set; }
        public string Advancement { get; set; }
        public Nullable<bool> RDFlag { get; set; }
        public Nullable<bool> ServiceCall { get; set; }
        public Nullable<long> cutby_memberid { get; set; }
        public Nullable<long> department { get; set; }
        public Nullable<int> Contact_ID { get; set; }
        public Nullable<int> Address_ID { get; set; }
        public string Location_in_plant { get; set; }
        public string SpecialInstructions { get; set; }
        public Nullable<int> ERID { get; set; }
        public Nullable<decimal> LabourTotalSell { get; set; }
        public Nullable<decimal> MaterialTotalSell { get; set; }
        public decimal JobCost_Tracking { get; set; }
        public decimal Billed_As_Quoted { get; set; }
        public Nullable<decimal> QuotedHoursTotal { get; set; }
        public Nullable<decimal> QuotedAmount { get; set; }
        public decimal TimeSheet_Percentage { get; set; }
        public Nullable<decimal> InvoicedNetTotal { get; set; }
        public Nullable<int> LocalTax1 { get; set; }
        public Nullable<int> LocalTax2 { get; set; }
        public Nullable<int> LocalTax3 { get; set; }
        public Nullable<decimal> HoursSpentQuoting { get; set; }
        public decimal expected_sales_value { get; set; }
        public decimal LaborCost { get; set; }
        public decimal MaterialCost { get; set; }
        public Nullable<long> Associate_WOProg_ID { get; set; }
        public Nullable<long> SP_MemberID { get; set; }
        public Nullable<int> quotedprice_type { get; set; }
        public long Tax1 { get; set; }
        public long Tax2 { get; set; }
        public long Tax3 { get; set; }
        public long tax4 { get; set; }
        public decimal ProgressBilled { get; set; }
        public decimal StillToBeBilled { get; set; }
        public decimal TotalTAndM { get; set; }
        public Nullable<decimal> grossmargin { get; set; }
        public Nullable<long> Customer_Consolidation { get; set; }
        public Nullable<System.DateTime> expected_startdate { get; set; }
        public Nullable<System.DateTime> expected_enddate { get; set; }
        public byte Hold { get; set; }
        public Nullable<long> MakeID { get; set; }
        public Nullable<long> ModelID { get; set; }
        public Nullable<long> ERWarranty { get; set; }
        public byte Apply_Discount { get; set; }
        public string CoreCompetency { get; set; }
        public string customersnotes { get; set; }
        public Nullable<System.DateTime> ExpectedCheckRun { get; set; }
        public Nullable<int> creditcard_payment { get; set; }
        public string collection_notes { get; set; }
        public Nullable<System.DateTime> last_email_date { get; set; }
        public Nullable<System.DateTime> last_faxed_date { get; set; }
        public Nullable<System.DateTime> invoice_paid_date { get; set; }
        public System.DateTime ts { get; set; }
        public int dayscredit { get; set; }
        public string whyhold { get; set; }
        public Nullable<int> onholdmemberid { get; set; }
        public Nullable<bool> vis_to_cust { get; set; }
        public Nullable<double> invoice_tax { get; set; }
        public Nullable<int> invoice_collection_status { get; set; }
        public bool iscredit { get; set; }
        public bool isrebill { get; set; }
        public string whycredit { get; set; }
        public Nullable<int> wocredit { get; set; }
        public decimal invoicebalance { get; set; }
        public decimal invoiceCreditAmt { get; set; }
        public string servicereportdesc { get; set; }
        public Nullable<int> custpo_member_id { get; set; }
        public Nullable<System.DateTime> custpo_dt { get; set; }
        public Nullable<bool> verbal_quote { get; set; }
        public Nullable<double> exp_labor { get; set; }
        public Nullable<int> assetid { get; set; }
        public Nullable<int> default_invoicetype { get; set; }
        public int auto_invoice { get; set; }
        public string glposting_instructions { get; set; }
        public Nullable<bool> isdownpayment { get; set; }
        public Nullable<int> schedule_status_id { get; set; }
        public Nullable<System.DateTime> notification_sent { get; set; }
        public Nullable<System.DateTime> survey_sent { get; set; }
        public Nullable<int> warranty { get; set; }
        public Nullable<System.DateTime> survey_finished { get; set; }
        public double benchmark_credit { get; set; }
        public Nullable<double> benchmark_labor_sell { get; set; }
        public Nullable<double> benchmark_material_sell { get; set; }
        public Nullable<int> parent_woprog_id { get; set; }
        public Nullable<bool> requires_quote_split { get; set; }
        public Nullable<decimal> this_wo_labour_cost { get; set; }
        public Nullable<decimal> this_wo_material_cost { get; set; }
        public Nullable<decimal> this_wo_labour_bench { get; set; }
        public Nullable<decimal> this_wo_material_bench { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<int> approved_by_parent_member_id { get; set; }
        public string default_labour_sell_gl { get; set; }
        public string default_material_sell_gl { get; set; }
        public double lag { get; set; }
        public Nullable<System.DateTime> max_waitingtobeinvoiced_dt { get; set; }
        public Nullable<bool> inspection_required { get; set; }
        public string inspection_link { get; set; }
        public Nullable<bool> labor_only { get; set; }
        public Nullable<bool> mat_only { get; set; }
        public Nullable<bool> sub_only { get; set; }
        public Nullable<double> fixed_labour_rate { get; set; }
        public Nullable<double> fixed_material_markup { get; set; }
        public Nullable<bool> use_fixed_labour_rate { get; set; }
        public bool use_fixed_material_markup { get; set; }
        public Nullable<bool> sustainability_project { get; set; }
        public Nullable<double> invoiced_currency_rate { get; set; }
        public Nullable<int> acting_ram { get; set; }
        public Nullable<int> jobtag_id { get; set; }
        public Nullable<double> no_of_days_left { get; set; }
        public Nullable<int> no_of_guys_left { get; set; }
        public Nullable<System.DateTime> last_date_worked { get; set; }
        public Nullable<System.DateTime> folders_last_checked { get; set; }
        public Nullable<bool> enableEditingScopeOnTimesheet { get; set; }
    }
}
