//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class wo_detail_current
    {
        public int wo_detail_current_id { get; set; }
        public int wo_detail_current_woprog_id { get; set; }
        public Nullable<int> wo_detail_current_rec_no { get; set; }
        public string wo_detail_current_type { get; set; }
        public int wo_detail_current_master_id { get; set; }
        public System.DateTime wo_detail_current_date_added { get; set; }
        public System.DateTime wo_detail_current_date_modified { get; set; }
        public string wo_detail_current_description { get; set; }
        public decimal wo_detail_current_qty_committed { get; set; }
        public decimal wo_detail_current_qty_invoiced { get; set; }
        public decimal wo_detail_current_price_cost { get; set; }
        public decimal wo_detail_current_price_sell { get; set; }
        public decimal wo_detail_current_price_unit { get; set; }
        public int wo_detail_current_added_by { get; set; }
        public Nullable<int> wo_detail_current_tax1 { get; set; }
        public Nullable<int> wo_detail_current_tax2 { get; set; }
        public Nullable<int> wo_detail_current_tax3 { get; set; }
        public Nullable<int> wo_detail_current_tax4 { get; set; }
        public Nullable<int> wo_detail_current_company_id { get; set; }
        public long wo_detail_current_bvwo { get; set; }
        public string wo_detail_current_code { get; set; }
        public string wo_detail_current_origin { get; set; }
        public Nullable<int> wo_detail_current_billtypeid { get; set; }
        public string wo_detail_current_issues { get; set; }
        public int memberid { get; set; }
        public int paytypeid { get; set; }
        public string wo_detail_current_notes { get; set; }
        public Nullable<decimal> wo_detail_current_qty_ordered { get; set; }
        public decimal wo_detail_current_discount { get; set; }
        public sbyte wo_detail_current_track_part { get; set; }
        public Nullable<System.DateTime> wo_detail_current_date_required { get; set; }
        public Nullable<int> wo_detail_current_consignment_id { get; set; }
        public Nullable<int> wo_detail_current_location_id { get; set; }
        public string wo_detail_current_added_by_module { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> blocks_schedule { get; set; }
        public Nullable<int> seg1_id { get; set; }
        public Nullable<int> seg2_id { get; set; }
        public Nullable<int> seg3_id { get; set; }
        public Nullable<int> division_id { get; set; }
        public int business_unit_id { get; set; }
        public string netsuite_purchaseorder_lineUniqueKey { get; set; }
        public string netsuite_salesorder_lineUniqueKey { get; set; }
        public string netsuite_vendorbill_internal_id { get; set; }
        public string netsuite_vendorpayment_internal_id { get; set; }
        public string netsuite_creditmemo_lineUniqueKey { get; set; }
        public Nullable<int> asset_id { get; set; }
        public Nullable<int> asset_unit { get; set; }
        public string external_id { get; set; }
        public string activity_code { get; set; }
        public string cost_element { get; set; }
        public string client_wo { get; set; }
        public string client_po { get; set; }
        public Nullable<int> child_woprog_id { get; set; }
        public Nullable<bool> partially_billed { get; set; }
    }
}
