//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class woprog_scheduler
    {
        public int woprog_id { get; set; }
        public string parts { get; set; }
        public string part_comment { get; set; }
        public string cust_comment { get; set; }
        public Nullable<System.DateTime> d_start { get; set; }
        public Nullable<System.TimeSpan> t_start { get; set; }
        public Nullable<bool> is_flexible { get; set; }
        public Nullable<bool> req_apprentice { get; set; }
        public Nullable<bool> req_electrician { get; set; }
        public Nullable<bool> req_truck { get; set; }
        public Nullable<int> job_length { get; set; }
    }
}
