//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class woprog_invoice_text
    {
        public int woprog_invoice_text_id { get; set; }
        public Nullable<int> woprog_invoice_text_woprog_id { get; set; }
        public string woprog_invoice_text_servicedates { get; set; }
    }
}
