//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    public partial class allowed_bu_on_wo : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        int fwoprog_id;
        [Indexed(Name = @"woprog_id")]
        public int woprog_id
        {
            get { return fwoprog_id; }
            set { SetPropertyValue<int>("woprog_id", ref fwoprog_id, value); }
        }
        int fallowed_bu_id;
        [Indexed(Name = @"allowed_bu_id")]
        public int allowed_bu_id
        {
            get { return fallowed_bu_id; }
            set { SetPropertyValue<int>("allowed_bu_id", ref fallowed_bu_id, value); }
        }
    }

}
