//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    [Indices(@"ar_notes_woprogid;ar_notes_memberid", "ar_notes_woprogid;ar_notes_memberid;ar_notes_note", "ar_notes_woprogid;ar_notes_note")]
    public partial class ar_notes : XPLiteObject
    {
        int far_notes_id;
        [Key(true)]
        public int ar_notes_id
        {
            get { return far_notes_id; }
            set { SetPropertyValue<int>("ar_notes_id", ref far_notes_id, value); }
        }
        int far_notes_woprogid;
        [Indexed(Name = @"ar_notes_woprogid")]
        public int ar_notes_woprogid
        {
            get { return far_notes_woprogid; }
            set { SetPropertyValue<int>("ar_notes_woprogid", ref far_notes_woprogid, value); }
        }
        int far_notes_memberid;
        [Indexed(Name = @"ar_notes_memberid")]
        public int ar_notes_memberid
        {
            get { return far_notes_memberid; }
            set { SetPropertyValue<int>("ar_notes_memberid", ref far_notes_memberid, value); }
        }
        string far_notes_note;
        [Size(3000)]
        public string ar_notes_note
        {
            get { return far_notes_note; }
            set { SetPropertyValue<string>("ar_notes_note", ref far_notes_note, value); }
        }
        bool far_notes_sent_to_bm;
        [Indexed(Name = @"ar_notes_sent_to_bm")]
        public bool ar_notes_sent_to_bm
        {
            get { return far_notes_sent_to_bm; }
            set { SetPropertyValue<bool>("ar_notes_sent_to_bm", ref far_notes_sent_to_bm, value); }
        }
    }

}
