//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    [Indices(@"member_id;cellphone_number_id")]
    public partial class cellphone_number_history : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        DateTime fdt;
        [Indexed(Name = @"dt")]
        public DateTime dt
        {
            get { return fdt; }
            set { SetPropertyValue<DateTime>("dt", ref fdt, value); }
        }
        int fmember_id;
        [Indexed(Name = @"member_id")]
        public int member_id
        {
            get { return fmember_id; }
            set { SetPropertyValue<int>("member_id", ref fmember_id, value); }
        }
        int fcellphone_number_id;
        [Indexed(Name = @"cellphone_number_id")]
        public int cellphone_number_id
        {
            get { return fcellphone_number_id; }
            set { SetPropertyValue<int>("cellphone_number_id", ref fcellphone_number_id, value); }
        }
        string fnotes;
        [Size(1000)]
        public string notes
        {
            get { return fnotes; }
            set { SetPropertyValue<string>("notes", ref fnotes, value); }
        }
    }

}
