//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    [Indices(@"core_responsibility;status", "core_responsibility;cr_group_id")]
    public partial class core_responsibilities : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        string fcore_responsibility;
        [Indexed(Name = @"core_responsibility")]
        [Size(1000)]
        public string core_responsibility
        {
            get { return fcore_responsibility; }
            set { SetPropertyValue<string>("core_responsibility", ref fcore_responsibility, value); }
        }
        int fmember_id;
        [Indexed(Name = @"member_id")]
        public int member_id
        {
            get { return fmember_id; }
            set { SetPropertyValue<int>("member_id", ref fmember_id, value); }
        }
        DateTime fdate_added;
        public DateTime date_added
        {
            get { return fdate_added; }
            set { SetPropertyValue<DateTime>("date_added", ref fdate_added, value); }
        }
        string fstatus;
        [Indexed(Name = @"status")]
        [Size(50)]
        public string status
        {
            get { return fstatus; }
            set { SetPropertyValue<string>("status", ref fstatus, value); }
        }
        string fdefault_target;
        [Size(500)]
        public string default_target
        {
            get { return fdefault_target; }
            set { SetPropertyValue<string>("default_target", ref fdefault_target, value); }
        }
        string fdescription;
        [Size(2000)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        string fannually;
        [Size(2000)]
        public string annually
        {
            get { return fannually; }
            set { SetPropertyValue<string>("annually", ref fannually, value); }
        }
        string fquarterly;
        [Size(2000)]
        public string quarterly
        {
            get { return fquarterly; }
            set { SetPropertyValue<string>("quarterly", ref fquarterly, value); }
        }
        string fmonthly;
        [Size(2000)]
        public string monthly
        {
            get { return fmonthly; }
            set { SetPropertyValue<string>("monthly", ref fmonthly, value); }
        }
        string fweekly;
        [Size(2000)]
        public string weekly
        {
            get { return fweekly; }
            set { SetPropertyValue<string>("weekly", ref fweekly, value); }
        }
        string fas_required;
        [Size(2000)]
        public string as_required
        {
            get { return fas_required; }
            set { SetPropertyValue<string>("as_required", ref fas_required, value); }
        }
        int fcr_group_id;
        [Indexed(Name = @"cr_group_id")]
        public int cr_group_id
        {
            get { return fcr_group_id; }
            set { SetPropertyValue<int>("cr_group_id", ref fcr_group_id, value); }
        }
        string fdaily;
        [Size(2000)]
        public string daily
        {
            get { return fdaily; }
            set { SetPropertyValue<string>("daily", ref fdaily, value); }
        }
    }

}
