//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    [Indices(@"cr_id;certificates_id")]
    public partial class cr_certificates : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        int fcr_id;
        [Indexed(Name = @"cr_id")]
        public int cr_id
        {
            get { return fcr_id; }
            set { SetPropertyValue<int>("cr_id", ref fcr_id, value); }
        }
        int fcertificates_id;
        [Indexed(Name = @"certificates_id")]
        public int certificates_id
        {
            get { return fcertificates_id; }
            set { SetPropertyValue<int>("certificates_id", ref fcertificates_id, value); }
        }
    }

}
