//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    [Indices(@"eritem_make;eritem_model", "eritem_make;eritem_model;eritem_dateadded")]
    public partial class eritem : XPLiteObject
    {
        int feritem_id;
        [Key(true)]
        public int eritem_id
        {
            get { return feritem_id; }
            set { SetPropertyValue<int>("eritem_id", ref feritem_id, value); }
        }
        string feritem_make;
        [Indexed(Name = @"eritem_make")]
        [Size(75)]
        public string eritem_make
        {
            get { return feritem_make; }
            set { SetPropertyValue<string>("eritem_make", ref feritem_make, value); }
        }
        string feritem_model;
        [Indexed(Name = @"eritem_model")]
        [Size(75)]
        public string eritem_model
        {
            get { return feritem_model; }
            set { SetPropertyValue<string>("eritem_model", ref feritem_model, value); }
        }
        int feritem_addedby;
        [Indexed(Name = @"eritem_addedby")]
        public int eritem_addedby
        {
            get { return feritem_addedby; }
            set { SetPropertyValue<int>("eritem_addedby", ref feritem_addedby, value); }
        }
        DateTime feritem_dateadded;
        [Indexed(Name = @"eritem_dateadded")]
        public DateTime eritem_dateadded
        {
            get { return feritem_dateadded; }
            set { SetPropertyValue<DateTime>("eritem_dateadded", ref feritem_dateadded, value); }
        }
        string feritem_notes;
        [Size(SizeAttribute.Unlimited)]
        public string eritem_notes
        {
            get { return feritem_notes; }
            set { SetPropertyValue<string>("eritem_notes", ref feritem_notes, value); }
        }
        string feritem_description;
        [Size(SizeAttribute.Unlimited)]
        public string eritem_description
        {
            get { return feritem_description; }
            set { SetPropertyValue<string>("eritem_description", ref feritem_description, value); }
        }
    }

}
