//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    public partial class hu_snapshot : XPLiteObject
    {
        int fbusiness_unit_id;
        [Key]
        public int business_unit_id
        {
            get { return fbusiness_unit_id; }
            set { SetPropertyValue<int>("business_unit_id", ref fbusiness_unit_id, value); }
        }
        DateTime flast_updated;
        public DateTime last_updated
        {
            get { return flast_updated; }
            set { SetPropertyValue<DateTime>("last_updated", ref flast_updated, value); }
        }
        double ftotalhours_last_year;
        public double totalhours_last_year
        {
            get { return ftotalhours_last_year; }
            set { SetPropertyValue<double>("totalhours_last_year", ref ftotalhours_last_year, value); }
        }
        int fcompany_id;
        public int company_id
        {
            get { return fcompany_id; }
            set { SetPropertyValue<int>("company_id", ref fcompany_id, value); }
        }
        double ftotalhours_last_month;
        public double totalhours_last_month
        {
            get { return ftotalhours_last_month; }
            set { SetPropertyValue<double>("totalhours_last_month", ref ftotalhours_last_month, value); }
        }
        double ftotalhours_this_month;
        public double totalhours_this_month
        {
            get { return ftotalhours_this_month; }
            set { SetPropertyValue<double>("totalhours_this_month", ref ftotalhours_this_month, value); }
        }
        double ftotalhours_this_year;
        public double totalhours_this_year
        {
            get { return ftotalhours_this_year; }
            set { SetPropertyValue<double>("totalhours_this_year", ref ftotalhours_this_year, value); }
        }
        double ftotal_quote_last_year;
        public double total_quote_last_year
        {
            get { return ftotal_quote_last_year; }
            set { SetPropertyValue<double>("total_quote_last_year", ref ftotal_quote_last_year, value); }
        }
        double ftotal_quote_last_month;
        public double total_quote_last_month
        {
            get { return ftotal_quote_last_month; }
            set { SetPropertyValue<double>("total_quote_last_month", ref ftotal_quote_last_month, value); }
        }
        double ftotal_quote_this_year;
        public double total_quote_this_year
        {
            get { return ftotal_quote_this_year; }
            set { SetPropertyValue<double>("total_quote_this_year", ref ftotal_quote_this_year, value); }
        }
        double ftotal_quote_this_month;
        public double total_quote_this_month
        {
            get { return ftotal_quote_this_month; }
            set { SetPropertyValue<double>("total_quote_this_month", ref ftotal_quote_this_month, value); }
        }
        double ftotalshop_last_year;
        public double totalshop_last_year
        {
            get { return ftotalshop_last_year; }
            set { SetPropertyValue<double>("totalshop_last_year", ref ftotalshop_last_year, value); }
        }
        double ftotalshop_last_month;
        public double totalshop_last_month
        {
            get { return ftotalshop_last_month; }
            set { SetPropertyValue<double>("totalshop_last_month", ref ftotalshop_last_month, value); }
        }
        double ftotalshop_this_year;
        public double totalshop_this_year
        {
            get { return ftotalshop_this_year; }
            set { SetPropertyValue<double>("totalshop_this_year", ref ftotalshop_this_year, value); }
        }
        double ftotalshop_this_month;
        public double totalshop_this_month
        {
            get { return ftotalshop_this_month; }
            set { SetPropertyValue<double>("totalshop_this_month", ref ftotalshop_this_month, value); }
        }
        double ftotalnewshop_last_year;
        public double totalnewshop_last_year
        {
            get { return ftotalnewshop_last_year; }
            set { SetPropertyValue<double>("totalnewshop_last_year", ref ftotalnewshop_last_year, value); }
        }
        double ftotalnewshop_last_month;
        public double totalnewshop_last_month
        {
            get { return ftotalnewshop_last_month; }
            set { SetPropertyValue<double>("totalnewshop_last_month", ref ftotalnewshop_last_month, value); }
        }
        double ftotalnewshop_this_year;
        public double totalnewshop_this_year
        {
            get { return ftotalnewshop_this_year; }
            set { SetPropertyValue<double>("totalnewshop_this_year", ref ftotalnewshop_this_year, value); }
        }
        double ftotalnewshop_this_month;
        public double totalnewshop_this_month
        {
            get { return ftotalnewshop_this_month; }
            set { SetPropertyValue<double>("totalnewshop_this_month", ref ftotalnewshop_this_month, value); }
        }
        double ftotalhours_this_week;
        public double totalhours_this_week
        {
            get { return ftotalhours_this_week; }
            set { SetPropertyValue<double>("totalhours_this_week", ref ftotalhours_this_week, value); }
        }
        double ftotalquote_this_week;
        public double totalquote_this_week
        {
            get { return ftotalquote_this_week; }
            set { SetPropertyValue<double>("totalquote_this_week", ref ftotalquote_this_week, value); }
        }
        double ftotalshop_this_week;
        public double totalshop_this_week
        {
            get { return ftotalshop_this_week; }
            set { SetPropertyValue<double>("totalshop_this_week", ref ftotalshop_this_week, value); }
        }
        double ftotalnewshop_this_week;
        public double totalnewshop_this_week
        {
            get { return ftotalnewshop_this_week; }
            set { SetPropertyValue<double>("totalnewshop_this_week", ref ftotalnewshop_this_week, value); }
        }
        double ftotalhours_six_month;
        public double totalhours_six_month
        {
            get { return ftotalhours_six_month; }
            set { SetPropertyValue<double>("totalhours_six_month", ref ftotalhours_six_month, value); }
        }
        double ftotalquote_six_month;
        public double totalquote_six_month
        {
            get { return ftotalquote_six_month; }
            set { SetPropertyValue<double>("totalquote_six_month", ref ftotalquote_six_month, value); }
        }
        double ftotalshop_six_month;
        public double totalshop_six_month
        {
            get { return ftotalshop_six_month; }
            set { SetPropertyValue<double>("totalshop_six_month", ref ftotalshop_six_month, value); }
        }
        double ftotalnewshop_six_month;
        public double totalnewshop_six_month
        {
            get { return ftotalnewshop_six_month; }
            set { SetPropertyValue<double>("totalnewshop_six_month", ref ftotalnewshop_six_month, value); }
        }
    }

}
