//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    public partial class huddle_task_comments : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        huddle_task fhuddle_task;
        [Association(@"huddle_task_commentsReferenceshuddle_task")]
        public huddle_task huddle_task
        {
            get { return fhuddle_task; }
            set { SetPropertyValue<huddle_task>("huddle_task", ref fhuddle_task, value); }
        }
        member fcreated_by;
        [Association(@"huddle_task_commentsReferencesmember")]
        public member created_by
        {
            get { return fcreated_by; }
            set { SetPropertyValue<member>("created_by", ref fcreated_by, value); }
        }
        DateTime fcreated_dt;
        public DateTime created_dt
        {
            get { return fcreated_dt; }
            set { SetPropertyValue<DateTime>("created_dt", ref fcreated_dt, value); }
        }
        string fcomment;
        [Size(SizeAttribute.Unlimited)]
        public string comment
        {
            get { return fcomment; }
            set { SetPropertyValue<string>("comment", ref fcomment, value); }
        }
    }

}
