//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    public partial class inventory_usage : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        DateTime fdt;
        public DateTime dt
        {
            get { return fdt; }
            set { SetPropertyValue<DateTime>("dt", ref fdt, value); }
        }
        string fmember_name;
        [Size(150)]
        public string member_name
        {
            get { return fmember_name; }
            set { SetPropertyValue<string>("member_name", ref fmember_name, value); }
        }
        int fcompany_id;
        [Indexed(Name = @"company_id")]
        public int company_id
        {
            get { return fcompany_id; }
            set { SetPropertyValue<int>("company_id", ref fcompany_id, value); }
        }
        string fbranch;
        [Size(50)]
        public string branch
        {
            get { return fbranch; }
            set { SetPropertyValue<string>("branch", ref fbranch, value); }
        }
        int fmaster_id;
        public int master_id
        {
            get { return fmaster_id; }
            set { SetPropertyValue<int>("master_id", ref fmaster_id, value); }
        }
        string fdescription;
        [Size(500)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        string flocation;
        [Size(150)]
        public string location
        {
            get { return flocation; }
            set { SetPropertyValue<string>("location", ref flocation, value); }
        }
        string fsection;
        public string section
        {
            get { return fsection; }
            set { SetPropertyValue<string>("section", ref fsection, value); }
        }
        double fqty_before;
        public double qty_before
        {
            get { return fqty_before; }
            set { SetPropertyValue<double>("qty_before", ref fqty_before, value); }
        }
        double fqty_after;
        public double qty_after
        {
            get { return fqty_after; }
            set { SetPropertyValue<double>("qty_after", ref fqty_after, value); }
        }
        double fqty_diff;
        public double qty_diff
        {
            get { return fqty_diff; }
            set { SetPropertyValue<double>("qty_diff", ref fqty_diff, value); }
        }
        double fdb_before;
        public double db_before
        {
            get { return fdb_before; }
            set { SetPropertyValue<double>("db_before", ref fdb_before, value); }
        }
        double fdb_after;
        public double db_after
        {
            get { return fdb_after; }
            set { SetPropertyValue<double>("db_after", ref fdb_after, value); }
        }
        double fdb_diff;
        public double db_diff
        {
            get { return fdb_diff; }
            set { SetPropertyValue<double>("db_diff", ref fdb_diff, value); }
        }
        double fcost_per;
        public double cost_per
        {
            get { return fcost_per; }
            set { SetPropertyValue<double>("cost_per", ref fcost_per, value); }
        }
        int fbusiness_unit_id;
        [Indexed(Name = @"idx_inventory_usage_business_unit_id")]
        public int business_unit_id
        {
            get { return fbusiness_unit_id; }
            set { SetPropertyValue<int>("business_unit_id", ref fbusiness_unit_id, value); }
        }
    }

}
