//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    [Indices(@"business_unit_id;end_date;start_date")]
    public partial class inventory_annual_count_header : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        int fcompany_id;
        [Indexed(Name = @"company_id")]
        public int company_id
        {
            get { return fcompany_id; }
            set { SetPropertyValue<int>("company_id", ref fcompany_id, value); }
        }
        DateTime fstart_date;
        [Indexed(@"end_date", Name = @"start_date")]
        public DateTime start_date
        {
            get { return fstart_date; }
            set { SetPropertyValue<DateTime>("start_date", ref fstart_date, value); }
        }
        DateTime fend_date;
        public DateTime end_date
        {
            get { return fend_date; }
            set { SetPropertyValue<DateTime>("end_date", ref fend_date, value); }
        }
        int fbusiness_unit_id;
        [Indexed(Name = @"idx_inventory_annual_count_header_business_unit_id")]
        public int business_unit_id
        {
            get { return fbusiness_unit_id; }
            set { SetPropertyValue<int>("business_unit_id", ref fbusiness_unit_id, value); }
        }
    }

}
