//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    [Indices(@"member_firstname;member_lastname", "member_membertype_id;member_contact_id", "cellphone_id;cellphone_number_id", "member_status;reports_to", "member_lastname;member_nickname", "member_id;member_status", "member_id;member_hrstatus_id;member_status")]
    public partial class member : XPLiteObject
    {
        int fmember_id;
        [Indexed(@"cellphone_number_id", Name = @"Member_ID_4")]
        [Key(true)]
        [Persistent(@"Member_ID")]
        public int member_id
        {
            get { return fmember_id; }
            set { SetPropertyValue<int>("member_id", ref fmember_id, value); }
        }
        int fmember_title;
        [Indexed(Name = @"member_title")]
        public int member_title
        {
            get { return fmember_title; }
            set { SetPropertyValue<int>("member_title", ref fmember_title, value); }
        }
        membertype fmember_membertype_id;
        [Indexed(@"member_status", Name = @"Member_MemberType_ID_2")]
        [Association(@"memberReferencesmembertype")]
        public membertype member_membertype_id
        {
            get { return fmember_membertype_id; }
            set { SetPropertyValue<membertype>("member_membertype_id", ref fmember_membertype_id, value); }
        }
        int fmember_div;
        [Indexed(Name = @"member_div")]
        public int member_div
        {
            get { return fmember_div; }
            set { SetPropertyValue<int>("member_div", ref fmember_div, value); }
        }
        string fmember_inv_bvnumber;
        [Indexed(Name = @"Member_Inv_BVNumber")]
        [Size(60)]
        [Persistent(@"Member_Inv_BVNumber")]
        public string member_inv_bvnumber
        {
            get { return fmember_inv_bvnumber; }
            set { SetPropertyValue<string>("member_inv_bvnumber", ref fmember_inv_bvnumber, value); }
        }
        string fmember_payroll_id;
        [Indexed(Name = @"Member_Payroll_ID")]
        [Size(20)]
        [Persistent(@"Member_Payroll_ID")]
        public string member_payroll_id
        {
            get { return fmember_payroll_id; }
            set { SetPropertyValue<string>("member_payroll_id", ref fmember_payroll_id, value); }
        }
        string fmember_user;
        [Indexed(Name = @"Member_User", Unique = true)]
        [Size(50)]
        [Persistent(@"Member_User")]
        public string member_user
        {
            get { return fmember_user; }
            set { SetPropertyValue<string>("member_user", ref fmember_user, value); }
        }
        string fmember_pass;
        public string member_pass
        {
            get { return fmember_pass; }
            set { SetPropertyValue<string>("member_pass", ref fmember_pass, value); }
        }
        string fmember_status;
        [Indexed(Name = @"Member_Status")]
        [Size(15)]
        [Persistent(@"Member_Status")]
        public string member_status
        {
            get { return fmember_status; }
            set { SetPropertyValue<string>("member_status", ref fmember_status, value); }
        }
        string fmember_firstname;
        [Indexed(Name = @"Member_FirstName_2")]
        [Size(25)]
        [Persistent(@"Member_FirstName")]
        public string member_firstname
        {
            get { return fmember_firstname; }
            set { SetPropertyValue<string>("member_firstname", ref fmember_firstname, value); }
        }
        string fmember_lastname;
        [Size(25)]
        [Persistent(@"Member_LastName")]
        public string member_lastname
        {
            get { return fmember_lastname; }
            set { SetPropertyValue<string>("member_lastname", ref fmember_lastname, value); }
        }
        string fmember_neemail;
        [Indexed(Name = @"Member_NEEmail")]
        public string member_neemail
        {
            get { return fmember_neemail; }
            set { SetPropertyValue<string>("member_neemail", ref fmember_neemail, value); }
        }
        string fmember_areacode;
        [Size(3)]
        [Persistent(@"Member_AreaCode")]
        public string member_areacode
        {
            get { return fmember_areacode; }
            set { SetPropertyValue<string>("member_areacode", ref fmember_areacode, value); }
        }
        string fmember_phonefirst;
        [Size(3)]
        [Persistent(@"Member_PhoneFirst")]
        public string member_phonefirst
        {
            get { return fmember_phonefirst; }
            set { SetPropertyValue<string>("member_phonefirst", ref fmember_phonefirst, value); }
        }
        string fmember_phonelast;
        [Size(4)]
        [Persistent(@"Member_PhoneLast")]
        public string member_phonelast
        {
            get { return fmember_phonelast; }
            set { SetPropertyValue<string>("member_phonelast", ref fmember_phonelast, value); }
        }
        string fmember_phoneextension;
        [Size(10)]
        [Persistent(@"Member_PhoneExtension")]
        public string member_phoneextension
        {
            get { return fmember_phoneextension; }
            set { SetPropertyValue<string>("member_phoneextension", ref fmember_phoneextension, value); }
        }
        int fpayroll_handler;
        [Indexed(Name = @"payroll_handler")]
        public int payroll_handler
        {
            get { return fpayroll_handler; }
            set { SetPropertyValue<int>("payroll_handler", ref fpayroll_handler, value); }
        }
        string fmember_add;
        [Persistent(@"Member_Add")]
        public string member_add
        {
            get { return fmember_add; }
            set { SetPropertyValue<string>("member_add", ref fmember_add, value); }
        }
        string fmember_city;
        [Persistent(@"Member_City")]
        public string member_city
        {
            get { return fmember_city; }
            set { SetPropertyValue<string>("member_city", ref fmember_city, value); }
        }
        string fmember_prov;
        [Size(10)]
        [Persistent(@"Member_Prov")]
        public string member_prov
        {
            get { return fmember_prov; }
            set { SetPropertyValue<string>("member_prov", ref fmember_prov, value); }
        }
        string fmember_country;
        [Size(5)]
        public string member_country
        {
            get { return fmember_country; }
            set { SetPropertyValue<string>("member_country", ref fmember_country, value); }
        }
        string fmember_postal;
        [Size(10)]
        [Persistent(@"Member_Postal")]
        public string member_postal
        {
            get { return fmember_postal; }
            set { SetPropertyValue<string>("member_postal", ref fmember_postal, value); }
        }
        string fmember_email;
        [Persistent(@"Member_Email")]
        public string member_email
        {
            get { return fmember_email; }
            set { SetPropertyValue<string>("member_email", ref fmember_email, value); }
        }
        string fmember_emergfirstname1;
        [Size(50)]
        [Persistent(@"Member_EmergFirstName1")]
        public string member_emergfirstname1
        {
            get { return fmember_emergfirstname1; }
            set { SetPropertyValue<string>("member_emergfirstname1", ref fmember_emergfirstname1, value); }
        }
        string fmember_emerglastname1;
        [Size(50)]
        [Persistent(@"Member_EmergLastName1")]
        public string member_emerglastname1
        {
            get { return fmember_emerglastname1; }
            set { SetPropertyValue<string>("member_emerglastname1", ref fmember_emerglastname1, value); }
        }
        string fmember_emergphonearea1;
        [Size(3)]
        [Persistent(@"Member_EmergPhoneArea1")]
        public string member_emergphonearea1
        {
            get { return fmember_emergphonearea1; }
            set { SetPropertyValue<string>("member_emergphonearea1", ref fmember_emergphonearea1, value); }
        }
        string fmember_emergphonefirst1;
        [Size(3)]
        [Persistent(@"Member_EmergPhoneFirst1")]
        public string member_emergphonefirst1
        {
            get { return fmember_emergphonefirst1; }
            set { SetPropertyValue<string>("member_emergphonefirst1", ref fmember_emergphonefirst1, value); }
        }
        string fmember_emergphonelast1;
        [Size(4)]
        [Persistent(@"Member_EmergPhoneLast1")]
        public string member_emergphonelast1
        {
            get { return fmember_emergphonelast1; }
            set { SetPropertyValue<string>("member_emergphonelast1", ref fmember_emergphonelast1, value); }
        }
        string fmember_emergfirstname2;
        [Size(50)]
        [Persistent(@"Member_EmergFirstName2")]
        public string member_emergfirstname2
        {
            get { return fmember_emergfirstname2; }
            set { SetPropertyValue<string>("member_emergfirstname2", ref fmember_emergfirstname2, value); }
        }
        string fmember_emerglastname2;
        [Size(50)]
        [Persistent(@"Member_EmergLastName2")]
        public string member_emerglastname2
        {
            get { return fmember_emerglastname2; }
            set { SetPropertyValue<string>("member_emerglastname2", ref fmember_emerglastname2, value); }
        }
        string fmember_emergphonearea2;
        [Size(3)]
        [Persistent(@"Member_EmergPhoneArea2")]
        public string member_emergphonearea2
        {
            get { return fmember_emergphonearea2; }
            set { SetPropertyValue<string>("member_emergphonearea2", ref fmember_emergphonearea2, value); }
        }
        string fmember_emergphonefirst2;
        [Size(3)]
        [Persistent(@"Member_EmergPhoneFirst2")]
        public string member_emergphonefirst2
        {
            get { return fmember_emergphonefirst2; }
            set { SetPropertyValue<string>("member_emergphonefirst2", ref fmember_emergphonefirst2, value); }
        }
        string fmember_emergphonelast2;
        [Size(4)]
        [Persistent(@"Member_EmergPhoneLast2")]
        public string member_emergphonelast2
        {
            get { return fmember_emergphonelast2; }
            set { SetPropertyValue<string>("member_emergphonelast2", ref fmember_emergphonelast2, value); }
        }
        string fmember_necellemail;
        [Persistent(@"Member_NECellEmail")]
        public string member_necellemail
        {
            get { return fmember_necellemail; }
            set { SetPropertyValue<string>("member_necellemail", ref fmember_necellemail, value); }
        }
        string fmember_necellareacode;
        [Size(3)]
        [Persistent(@"Member_NECellAreaCode")]
        public string member_necellareacode
        {
            get { return fmember_necellareacode; }
            set { SetPropertyValue<string>("member_necellareacode", ref fmember_necellareacode, value); }
        }
        string fmember_necellphonefirst;
        [Size(3)]
        [Persistent(@"Member_NECellPhoneFirst")]
        public string member_necellphonefirst
        {
            get { return fmember_necellphonefirst; }
            set { SetPropertyValue<string>("member_necellphonefirst", ref fmember_necellphonefirst, value); }
        }
        string fmember_necellphonelast;
        [Size(4)]
        [Persistent(@"Member_NECellPhoneLast")]
        public string member_necellphonelast
        {
            get { return fmember_necellphonelast; }
            set { SetPropertyValue<string>("member_necellphonelast", ref fmember_necellphonelast, value); }
        }
        string fmember_truck;
        [Size(10)]
        [Persistent(@"Member_Truck")]
        public string member_truck
        {
            get { return fmember_truck; }
            set { SetPropertyValue<string>("member_truck", ref fmember_truck, value); }
        }
        DateTime fmember_birthdate;
        [Persistent(@"Member_BirthDate")]
        public DateTime member_birthdate
        {
            get { return fmember_birthdate; }
            set { SetPropertyValue<DateTime>("member_birthdate", ref fmember_birthdate, value); }
        }
        DateTime fmember_startdate;
        [Indexed(@"member_termdate", Name = @"member_company_id_5")]
        public DateTime member_startdate
        {
            get { return fmember_startdate; }
            set { SetPropertyValue<DateTime>("member_startdate", ref fmember_startdate, value); }
        }
        DateTime fmember_termdate;
        [Persistent(@"Member_TermDate")]
        public DateTime member_termdate
        {
            get { return fmember_termdate; }
            set { SetPropertyValue<DateTime>("member_termdate", ref fmember_termdate, value); }
        }
        int fpaytype_id;
        [Indexed(Name = @"paytype_id")]
        public int paytype_id
        {
            get { return fpaytype_id; }
            set { SetPropertyValue<int>("paytype_id", ref fpaytype_id, value); }
        }
        int freceive_stat_pay;
        public int receive_stat_pay
        {
            get { return freceive_stat_pay; }
            set { SetPropertyValue<int>("receive_stat_pay", ref freceive_stat_pay, value); }
        }
        string fmember_paytype;
        [Size(50)]
        public string member_paytype
        {
            get { return fmember_paytype; }
            set { SetPropertyValue<string>("member_paytype", ref fmember_paytype, value); }
        }
        DateTime fmember_lastraise;
        [Persistent(@"Member_LastRaise")]
        public DateTime member_lastraise
        {
            get { return fmember_lastraise; }
            set { SetPropertyValue<DateTime>("member_lastraise", ref fmember_lastraise, value); }
        }
        DateTime fmember_nextraise;
        [Persistent(@"Member_NextRaise")]
        public DateTime member_nextraise
        {
            get { return fmember_nextraise; }
            set { SetPropertyValue<DateTime>("member_nextraise", ref fmember_nextraise, value); }
        }
        double fmember_holiday;
        [Persistent(@"Member_Holiday")]
        public double member_holiday
        {
            get { return fmember_holiday; }
            set { SetPropertyValue<double>("member_holiday", ref fmember_holiday, value); }
        }
        double fmember_holidaytaken;
        [Persistent(@"Member_HolidayTaken")]
        public double member_holidaytaken
        {
            get { return fmember_holidaytaken; }
            set { SetPropertyValue<double>("member_holidaytaken", ref fmember_holidaytaken, value); }
        }
        int fvacation_interval_1;
        public int vacation_interval_1
        {
            get { return fvacation_interval_1; }
            set { SetPropertyValue<int>("vacation_interval_1", ref fvacation_interval_1, value); }
        }
        int fvacation_interval_2;
        public int vacation_interval_2
        {
            get { return fvacation_interval_2; }
            set { SetPropertyValue<int>("vacation_interval_2", ref fvacation_interval_2, value); }
        }
        int fvacation_interval_3;
        public int vacation_interval_3
        {
            get { return fvacation_interval_3; }
            set { SetPropertyValue<int>("vacation_interval_3", ref fvacation_interval_3, value); }
        }
        double fvacation_amount_1;
        public double vacation_amount_1
        {
            get { return fvacation_amount_1; }
            set { SetPropertyValue<double>("vacation_amount_1", ref fvacation_amount_1, value); }
        }
        double fvacation_amount_2;
        public double vacation_amount_2
        {
            get { return fvacation_amount_2; }
            set { SetPropertyValue<double>("vacation_amount_2", ref fvacation_amount_2, value); }
        }
        double fvacation_amount_3;
        public double vacation_amount_3
        {
            get { return fvacation_amount_3; }
            set { SetPropertyValue<double>("vacation_amount_3", ref fvacation_amount_3, value); }
        }
        int flast_anniversary;
        public int last_anniversary
        {
            get { return flast_anniversary; }
            set { SetPropertyValue<int>("last_anniversary", ref flast_anniversary, value); }
        }
        double fmember_unpaid;
        [Persistent(@"Member_Unpaid")]
        public double member_unpaid
        {
            get { return fmember_unpaid; }
            set { SetPropertyValue<double>("member_unpaid", ref fmember_unpaid, value); }
        }
        double fmember_sickdays;
        [Persistent(@"Member_SickDays")]
        public double member_sickdays
        {
            get { return fmember_sickdays; }
            set { SetPropertyValue<double>("member_sickdays", ref fmember_sickdays, value); }
        }
        double fmember_lateoccur;
        [Persistent(@"Member_LateOccur")]
        public double member_lateoccur
        {
            get { return fmember_lateoccur; }
            set { SetPropertyValue<double>("member_lateoccur", ref fmember_lateoccur, value); }
        }
        string fmember_driverslicence;
        [Size(50)]
        [Persistent(@"Member_DriversLicence")]
        public string member_driverslicence
        {
            get { return fmember_driverslicence; }
            set { SetPropertyValue<string>("member_driverslicence", ref fmember_driverslicence, value); }
        }
        string fmember_sin;
        [Size(50)]
        public string member_sin
        {
            get { return fmember_sin; }
            set { SetPropertyValue<string>("member_sin", ref fmember_sin, value); }
        }
        string fmember_eleclicence;
        [Size(50)]
        [Persistent(@"Member_ElecLicence")]
        public string member_eleclicence
        {
            get { return fmember_eleclicence; }
            set { SetPropertyValue<string>("member_eleclicence", ref fmember_eleclicence, value); }
        }
        int fmember_member_id;
        [Persistent(@"Member_Member_ID")]
        public int member_member_id
        {
            get { return fmember_member_id; }
            set { SetPropertyValue<int>("member_member_id", ref fmember_member_id, value); }
        }
        DateTime fmember_lastdatetime;
        public DateTime member_lastdatetime
        {
            get { return fmember_lastdatetime; }
            set { SetPropertyValue<DateTime>("member_lastdatetime", ref fmember_lastdatetime, value); }
        }
        DateTime fmember_dateadded;
        public DateTime member_dateadded
        {
            get { return fmember_dateadded; }
            set { SetPropertyValue<DateTime>("member_dateadded", ref fmember_dateadded, value); }
        }
        sbyte fmember_er_flag;
        [Persistent(@"Member_ER_Flag")]
        public sbyte member_er_flag
        {
            get { return fmember_er_flag; }
            set { SetPropertyValue<sbyte>("member_er_flag", ref fmember_er_flag, value); }
        }
        bool fmember_level;
        [Persistent(@"Member_Level")]
        public bool member_level
        {
            get { return fmember_level; }
            set { SetPropertyValue<bool>("member_level", ref fmember_level, value); }
        }
        bool fcan_quote;
        public bool can_quote
        {
            get { return fcan_quote; }
            set { SetPropertyValue<bool>("can_quote", ref fcan_quote, value); }
        }
        int flast_quote_id;
        public int last_quote_id
        {
            get { return flast_quote_id; }
            set { SetPropertyValue<int>("last_quote_id", ref flast_quote_id, value); }
        }
        string fmember_alternate_cell;
        [Size(50)]
        [Persistent(@"Member_Alternate_Cell")]
        public string member_alternate_cell
        {
            get { return fmember_alternate_cell; }
            set { SetPropertyValue<string>("member_alternate_cell", ref fmember_alternate_cell, value); }
        }
        string femployeeid;
        [Size(11)]
        [Persistent(@"EmployeeID")]
        public string employeeid
        {
            get { return femployeeid; }
            set { SetPropertyValue<string>("employeeid", ref femployeeid, value); }
        }
        string femplogon;
        [Persistent(@"EmpLogon")]
        [ColumnDefaultValue("")]
        public string emplogon
        {
            get { return femplogon; }
            set { SetPropertyValue<string>("emplogon", ref femplogon, value); }
        }
        string fmember_employeenotes;
        [Size(750)]
        [Persistent(@"Member_EmployeeNotes")]
        public string member_employeenotes
        {
            get { return fmember_employeenotes; }
            set { SetPropertyValue<string>("member_employeenotes", ref fmember_employeenotes, value); }
        }
        bool fmember_ts_watch;
        [Persistent(@"Member_TS_Watch")]
        public bool member_ts_watch
        {
            get { return fmember_ts_watch; }
            set { SetPropertyValue<bool>("member_ts_watch", ref fmember_ts_watch, value); }
        }
        int fmember_time_to_stat;
        public int member_time_to_stat
        {
            get { return fmember_time_to_stat; }
            set { SetPropertyValue<int>("member_time_to_stat", ref fmember_time_to_stat, value); }
        }
        int fmember_apprentice_level;
        [Persistent(@"Member_Apprentice_Level")]
        public int member_apprentice_level
        {
            get { return fmember_apprentice_level; }
            set { SetPropertyValue<int>("member_apprentice_level", ref fmember_apprentice_level, value); }
        }
        bool fshow_quote_help;
        public bool show_quote_help
        {
            get { return fshow_quote_help; }
            set { SetPropertyValue<bool>("show_quote_help", ref fshow_quote_help, value); }
        }
        int fmember_contact_id;
        [Indexed(Name = @"Member_Contact_ID")]
        [Persistent(@"Member_Contact_ID")]
        public int member_contact_id
        {
            get { return fmember_contact_id; }
            set { SetPropertyValue<int>("member_contact_id", ref fmember_contact_id, value); }
        }
        DateTime fpassworddatechange;
        [Persistent(@"PasswordDateChange")]
        public DateTime passworddatechange
        {
            get { return fpassworddatechange; }
            set { SetPropertyValue<DateTime>("passworddatechange", ref fpassworddatechange, value); }
        }
        int fmember_default_location;
        [Indexed(Name = @"member_default_location")]
        public int member_default_location
        {
            get { return fmember_default_location; }
            set { SetPropertyValue<int>("member_default_location", ref fmember_default_location, value); }
        }
        int fmember_default_page;
        [Indexed(Name = @"member_default_page")]
        public int member_default_page
        {
            get { return fmember_default_page; }
            set { SetPropertyValue<int>("member_default_page", ref fmember_default_page, value); }
        }
        string fmember_nickname;
        [Indexed(Name = @"member_nickname")]
        [Size(50)]
        public string member_nickname
        {
            get { return fmember_nickname; }
            set { SetPropertyValue<string>("member_nickname", ref fmember_nickname, value); }
        }
        string fmember_middleinitial;
        [Size(1)]
        public string member_middleinitial
        {
            get { return fmember_middleinitial; }
            set { SetPropertyValue<string>("member_middleinitial", ref fmember_middleinitial, value); }
        }
        string fmember_hasdependants;
        [Size(3)]
        public string member_hasdependants
        {
            get { return fmember_hasdependants; }
            set { SetPropertyValue<string>("member_hasdependants", ref fmember_hasdependants, value); }
        }
        int fmember_hrstatus_id;
        [Indexed(Name = @"member_hrstatus_id")]
        public int member_hrstatus_id
        {
            get { return fmember_hrstatus_id; }
            set { SetPropertyValue<int>("member_hrstatus_id", ref fmember_hrstatus_id, value); }
        }
        string fmember_pecell_area;
        [Size(3)]
        public string member_pecell_area
        {
            get { return fmember_pecell_area; }
            set { SetPropertyValue<string>("member_pecell_area", ref fmember_pecell_area, value); }
        }
        string fmember_pecell_pref;
        [Size(3)]
        public string member_pecell_pref
        {
            get { return fmember_pecell_pref; }
            set { SetPropertyValue<string>("member_pecell_pref", ref fmember_pecell_pref, value); }
        }
        string fmember_pecell_suff;
        [Size(4)]
        public string member_pecell_suff
        {
            get { return fmember_pecell_suff; }
            set { SetPropertyValue<string>("member_pecell_suff", ref fmember_pecell_suff, value); }
        }
        string fmember_ldap_user;
        [Size(50)]
        public string member_ldap_user
        {
            get { return fmember_ldap_user; }
            set { SetPropertyValue<string>("member_ldap_user", ref fmember_ldap_user, value); }
        }
        sbyte fgets_vehicle;
        public sbyte gets_vehicle
        {
            get { return fgets_vehicle; }
            set { SetPropertyValue<sbyte>("gets_vehicle", ref fgets_vehicle, value); }
        }
        sbyte fgets_phone;
        public sbyte gets_phone
        {
            get { return fgets_phone; }
            set { SetPropertyValue<sbyte>("gets_phone", ref fgets_phone, value); }
        }
        sbyte fgets_laptop;
        public sbyte gets_laptop
        {
            get { return fgets_laptop; }
            set { SetPropertyValue<sbyte>("gets_laptop", ref fgets_laptop, value); }
        }
        int freports_to;
        [Indexed(Name = @"reports_to")]
        public int reports_to
        {
            get { return freports_to; }
            set { SetPropertyValue<int>("reports_to", ref freports_to, value); }
        }
        sbyte fhas_comp;
        public sbyte has_comp
        {
            get { return fhas_comp; }
            set { SetPropertyValue<sbyte>("has_comp", ref fhas_comp, value); }
        }
        string fcomp_details;
        [Size(2500)]
        public string comp_details
        {
            get { return fcomp_details; }
            set { SetPropertyValue<string>("comp_details", ref fcomp_details, value); }
        }
        string foffer_notes;
        [Size(2500)]
        public string offer_notes
        {
            get { return foffer_notes; }
            set { SetPropertyValue<string>("offer_notes", ref foffer_notes, value); }
        }
        string fmember_fullname;
        [Indexed(Name = @"member_fullname")]
        public string member_fullname
        {
            get { return fmember_fullname; }
            set { SetPropertyValue<string>("member_fullname", ref fmember_fullname, value); }
        }
        string fmember_windows_password;
        [Indexed(Name = @"member_windows_password")]
        public string member_windows_password
        {
            get { return fmember_windows_password; }
            set { SetPropertyValue<string>("member_windows_password", ref fmember_windows_password, value); }
        }
        int fcellphone_id;
        [Indexed(Name = @"cellphone_id")]
        public int cellphone_id
        {
            get { return fcellphone_id; }
            set { SetPropertyValue<int>("cellphone_id", ref fcellphone_id, value); }
        }
        cellphone_number fcellphone_number_id;
        [Indexed(Name = @"cellphone_number_id")]
        [Association(@"memberReferencescellphone_number")]
        public cellphone_number cellphone_number_id
        {
            get { return fcellphone_number_id; }
            set { SetPropertyValue<cellphone_number>("cellphone_number_id", ref fcellphone_number_id, value); }
        }
        int fis_us_boardmember;
        [Persistent(@"is_US_boardmember")]
        public int is_us_boardmember
        {
            get { return fis_us_boardmember; }
            set { SetPropertyValue<int>("is_us_boardmember", ref fis_us_boardmember, value); }
        }
        int fis_can_boardmember;
        [Persistent(@"is_CAN_boardmember")]
        public int is_can_boardmember
        {
            get { return fis_can_boardmember; }
            set { SetPropertyValue<int>("is_can_boardmember", ref fis_can_boardmember, value); }
        }
        bool fforce_beta;
        public bool force_beta
        {
            get { return fforce_beta; }
            set { SetPropertyValue<bool>("force_beta", ref fforce_beta, value); }
        }
        string fbonus_notes;
        [Size(2000)]
        public string bonus_notes
        {
            get { return fbonus_notes; }
            set { SetPropertyValue<string>("bonus_notes", ref fbonus_notes, value); }
        }
        int fscheduled_by;
        [Indexed(Name = @"scheduled_by")]
        public int scheduled_by
        {
            get { return fscheduled_by; }
            set { SetPropertyValue<int>("scheduled_by", ref fscheduled_by, value); }
        }
        string fapprentice_contract;
        [Size(50)]
        public string apprentice_contract
        {
            get { return fapprentice_contract; }
            set { SetPropertyValue<string>("apprentice_contract", ref fapprentice_contract, value); }
        }
        bool fgets_barcodescanner;
        public bool gets_barcodescanner
        {
            get { return fgets_barcodescanner; }
            set { SetPropertyValue<bool>("gets_barcodescanner", ref fgets_barcodescanner, value); }
        }
        bool fgets_businesscards;
        public bool gets_businesscards
        {
            get { return fgets_businesscards; }
            set { SetPropertyValue<bool>("gets_businesscards", ref fgets_businesscards, value); }
        }
        bool fgets_directdeposit;
        public bool gets_directdeposit
        {
            get { return fgets_directdeposit; }
            set { SetPropertyValue<bool>("gets_directdeposit", ref fgets_directdeposit, value); }
        }
        bool fgets_neemail;
        public bool gets_neemail
        {
            get { return fgets_neemail; }
            set { SetPropertyValue<bool>("gets_neemail", ref fgets_neemail, value); }
        }
        bool fgets_phoneext;
        public bool gets_phoneext
        {
            get { return fgets_phoneext; }
            set { SetPropertyValue<bool>("gets_phoneext", ref fgets_phoneext, value); }
        }
        bool fdisable_ldap_sync;
        public bool disable_ldap_sync
        {
            get { return fdisable_ldap_sync; }
            set { SetPropertyValue<bool>("disable_ldap_sync", ref fdisable_ldap_sync, value); }
        }
        string fbenefits_id;
        public string benefits_id
        {
            get { return fbenefits_id; }
            set { SetPropertyValue<string>("benefits_id", ref fbenefits_id, value); }
        }
        string flife_insurance_id;
        public string life_insurance_id
        {
            get { return flife_insurance_id; }
            set { SetPropertyValue<string>("life_insurance_id", ref flife_insurance_id, value); }
        }
        DateTime fbenefits_startdate;
        public DateTime benefits_startdate
        {
            get { return fbenefits_startdate; }
            set { SetPropertyValue<DateTime>("benefits_startdate", ref fbenefits_startdate, value); }
        }
        bool fpart_time;
        public bool part_time
        {
            get { return fpart_time; }
            set { SetPropertyValue<bool>("part_time", ref fpart_time, value); }
        }
        int fvendor_id;
        public int vendor_id
        {
            get { return fvendor_id; }
            set { SetPropertyValue<int>("vendor_id", ref fvendor_id, value); }
        }
        string fcolor;
        [Size(7)]
        public string color
        {
            get { return fcolor; }
            set { SetPropertyValue<string>("color", ref fcolor, value); }
        }
        sbyte finclude_in_mobile_contactlist;
        public sbyte include_in_mobile_contactlist
        {
            get { return finclude_in_mobile_contactlist; }
            set { SetPropertyValue<sbyte>("include_in_mobile_contactlist", ref finclude_in_mobile_contactlist, value); }
        }
        DateTime flast_mobile_login;
        public DateTime last_mobile_login
        {
            get { return flast_mobile_login; }
            set { SetPropertyValue<DateTime>("last_mobile_login", ref flast_mobile_login, value); }
        }
        double fmember_wage;
        public double member_wage
        {
            get { return fmember_wage; }
            set { SetPropertyValue<double>("member_wage", ref fmember_wage, value); }
        }
        sbyte fmember_probation_email_sent;
        public sbyte member_probation_email_sent
        {
            get { return fmember_probation_email_sent; }
            set { SetPropertyValue<sbyte>("member_probation_email_sent", ref fmember_probation_email_sent, value); }
        }
        int factive_offer_id;
        public int active_offer_id
        {
            get { return factive_offer_id; }
            set { SetPropertyValue<int>("active_offer_id", ref factive_offer_id, value); }
        }
        int fseg1_id;
        public int seg1_id
        {
            get { return fseg1_id; }
            set { SetPropertyValue<int>("seg1_id", ref fseg1_id, value); }
        }
        int fseg2_id;
        public int seg2_id
        {
            get { return fseg2_id; }
            set { SetPropertyValue<int>("seg2_id", ref fseg2_id, value); }
        }
        int fseg3_id;
        public int seg3_id
        {
            get { return fseg3_id; }
            set { SetPropertyValue<int>("seg3_id", ref fseg3_id, value); }
        }
        business_unit fbusiness_unit_id;
        [Association(@"memberReferencesbusiness_unit")]
        public business_unit business_unit_id
        {
            get { return fbusiness_unit_id; }
            set { SetPropertyValue<business_unit>("business_unit_id", ref fbusiness_unit_id, value); }
        }
        uint fmember_company_id;
        public uint member_company_id
        {
            get { return fmember_company_id; }
            set { SetPropertyValue<uint>("member_company_id", ref fmember_company_id, value); }
        }
        int factive_ticket_id;
        public int active_ticket_id
        {
            get { return factive_ticket_id; }
            set { SetPropertyValue<int>("active_ticket_id", ref factive_ticket_id, value); }
        }
        bool fsent_welcome_email;
        public bool sent_welcome_email
        {
            get { return fsent_welcome_email; }
            set { SetPropertyValue<bool>("sent_welcome_email", ref fsent_welcome_email, value); }
        }
        bool frequest_password_reset_flag;
        public bool request_password_reset_flag
        {
            get { return frequest_password_reset_flag; }
            set { SetPropertyValue<bool>("request_password_reset_flag", ref frequest_password_reset_flag, value); }
        }
        sbyte fauto_vacation_payout;
        [ColumnDefaultValue(0)]
        public sbyte auto_vacation_payout
        {
            get { return fauto_vacation_payout; }
            set { SetPropertyValue<sbyte>("auto_vacation_payout", ref fauto_vacation_payout, value); }
        }
        string fnetsuite_internal_id;
        [Size(35)]
        public string netsuite_internal_id
        {
            get { return fnetsuite_internal_id; }
            set { SetPropertyValue<string>("netsuite_internal_id", ref fnetsuite_internal_id, value); }
        }
        [Association(@"huddleReferencesmember")]
        public XPCollection<huddle> huddles { get { return GetCollection<huddle>("huddles"); } }
        [Association(@"huddleReferencesmember1")]
        public XPCollection<huddle> huddles1 { get { return GetCollection<huddle>("huddles1"); } }
        [Association(@"huddle_taskReferencesmember")]
        public XPCollection<huddle_task> huddle_tasks { get { return GetCollection<huddle_task>("huddle_tasks"); } }
        [Association(@"huddle_task_commentsReferencesmember")]
        public XPCollection<huddle_task_comments> huddle_task_commentss { get { return GetCollection<huddle_task_comments>("huddle_task_commentss"); } }
        [Association(@"huddle_userReferencesmember")]
        public XPCollection<huddle_user> huddle_users { get { return GetCollection<huddle_user>("huddle_users"); } }
        [Association(@"poprogstatusReferencesmember")]
        public XPCollection<poprogstatus> poprogstatusCollection { get { return GetCollection<poprogstatus>("poprogstatusCollection"); } }
        [Association(@"r_engine_permissionReferencesmember")]
        public XPCollection<r_engine_permission> r_engine_permissions { get { return GetCollection<r_engine_permission>("r_engine_permissions"); } }
        [Association(@"shopping_cartReferencesmember")]
        public XPCollection<shopping_cart> shopping_carts { get { return GetCollection<shopping_cart>("shopping_carts"); } }
        [Association(@"shopping_cart_headerReferencesmember")]
        public XPCollection<shopping_cart_header> shopping_cart_headers { get { return GetCollection<shopping_cart_header>("shopping_cart_headers"); } }
        [Association(@"signatureReferencesmember")]
        public XPCollection<signature> signatures { get { return GetCollection<signature>("signatures"); } }
        [Association(@"ticket_groupReferencesmember")]
        public XPCollection<ticket_group> ticket_groups { get { return GetCollection<ticket_group>("ticket_groups"); } }
        [Association(@"ticket_memberviewReferencesmember")]
        public XPCollection<ticket_memberview> ticket_memberviews { get { return GetCollection<ticket_memberview>("ticket_memberviews"); } }
        [Association(@"ticket_tasksReferencesmember")]
        public XPCollection<ticket_tasks> ticket_taskss { get { return GetCollection<ticket_tasks>("ticket_taskss"); } }
        [Association(@"ticket_voteReferencesmember")]
        public XPCollection<ticket_vote> ticket_votes { get { return GetCollection<ticket_vote>("ticket_votes"); } }
        [Association(@"ticketheaderReferencesmember")]
        public XPCollection<ticketheader> ticketheaders { get { return GetCollection<ticketheader>("ticketheaders"); } }
        [Association(@"ticketheaderReferencesmember1")]
        public XPCollection<ticketheader> ticketheaders1 { get { return GetCollection<ticketheader>("ticketheaders1"); } }
        [Association(@"ticketheaderReferencesmember2")]
        public XPCollection<ticketheader> ticketheaders2 { get { return GetCollection<ticketheader>("ticketheaders2"); } }
        [Association(@"ticketheaderReferencesmember3")]
        public XPCollection<ticketheader> ticketheaders3 { get { return GetCollection<ticketheader>("ticketheaders3"); } }
        [Association(@"ticketissuesReferencesmember")]
        public XPCollection<ticketissues> ticketissuesCollection { get { return GetCollection<ticketissues>("ticketissuesCollection"); } }
        [Association(@"ticketmanagerReferencesmember")]
        public XPCollection<ticketmanager> ticketmanagers { get { return GetCollection<ticketmanager>("ticketmanagers"); } }
        [Association(@"n2_user_profileReferencesmember")]
        public XPCollection<n2_user_profile> n2_user_profiles { get { return GetCollection<n2_user_profile>("n2_user_profiles"); } }
        [Association(@"membertime_tagsReferencesmember")]
        public XPCollection<membertime_tags> membertime_tagss { get { return GetCollection<membertime_tags>("membertime_tagss"); } }
        [Association(@"memberpageReferencesmember")]
        public XPCollection<memberpage> memberpages { get { return GetCollection<memberpage>("memberpages"); } }
        [Association(@"memberpageprivilegeReferencesmember")]
        public XPCollection<memberpageprivilege> memberpageprivileges { get { return GetCollection<memberpageprivilege>("memberpageprivileges"); } }
        [Association(@"breaktimeReferencesmember")]
        public XPCollection<breaktime> breaktimes { get { return GetCollection<breaktime>("breaktimes"); } }
        [Association(@"breaktimeReferencesmember1")]
        public XPCollection<breaktime> breaktimes1 { get { return GetCollection<breaktime>("breaktimes1"); } }
        [Association(@"visible_business_unitsReferencesmember")]
        public XPCollection<visible_business_units> visible_business_unitss { get { return GetCollection<visible_business_units>("visible_business_unitss"); } }
    }

}
