//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    public partial class member_fvr_template_detail : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        int fhdr_id;
        public int hdr_id
        {
            get { return fhdr_id; }
            set { SetPropertyValue<int>("hdr_id", ref fhdr_id, value); }
        }
        int fpage_id;
        public int page_id
        {
            get { return fpage_id; }
            set { SetPropertyValue<int>("page_id", ref fpage_id, value); }
        }
        int ffile_id;
        public int file_id
        {
            get { return ffile_id; }
            set { SetPropertyValue<int>("file_id", ref ffile_id, value); }
        }
        string furl;
        [Size(255)]
        public string url
        {
            get { return furl; }
            set { SetPropertyValue<string>("url", ref furl, value); }
        }
        bool fupload_required;
        public bool upload_required
        {
            get { return fupload_required; }
            set { SetPropertyValue<bool>("upload_required", ref fupload_required, value); }
        }
        bool fis_selected;
        public bool is_selected
        {
            get { return fis_selected; }
            set { SetPropertyValue<bool>("is_selected", ref fis_selected, value); }
        }
    }

}
