//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    public partial class member_timesheet_accuracy : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        int fbusiness_unit_id;
        public int business_unit_id
        {
            get { return fbusiness_unit_id; }
            set { SetPropertyValue<int>("business_unit_id", ref fbusiness_unit_id, value); }
        }
        int fmember_id;
        public int member_id
        {
            get { return fmember_id; }
            set { SetPropertyValue<int>("member_id", ref fmember_id, value); }
        }
        double fpct;
        [ColumnDefaultValue(0)]
        public double pct
        {
            get { return fpct; }
            set { SetPropertyValue<double>("pct", ref fpct, value); }
        }
    }

}
