//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    public partial class messageboard_chat : XPLiteObject
    {
        int fmessageboard_chat_id;
        [Key(true)]
        public int messageboard_chat_id
        {
            get { return fmessageboard_chat_id; }
            set { SetPropertyValue<int>("messageboard_chat_id", ref fmessageboard_chat_id, value); }
        }
        int fmessageboard_memberid;
        public int messageboard_memberid
        {
            get { return fmessageboard_memberid; }
            set { SetPropertyValue<int>("messageboard_memberid", ref fmessageboard_memberid, value); }
        }
        DateTime fmessageboard_date;
        public DateTime messageboard_date
        {
            get { return fmessageboard_date; }
            set { SetPropertyValue<DateTime>("messageboard_date", ref fmessageboard_date, value); }
        }
        string fmessageboard_text;
        [Size(1000)]
        public string messageboard_text
        {
            get { return fmessageboard_text; }
            set { SetPropertyValue<string>("messageboard_text", ref fmessageboard_text, value); }
        }
        int fmessageboard_companyid;
        public int messageboard_companyid
        {
            get { return fmessageboard_companyid; }
            set { SetPropertyValue<int>("messageboard_companyid", ref fmessageboard_companyid, value); }
        }
        int fbusiness_unit_id;
        [Indexed(Name = @"idx_messageboard_chat_business_unit_id")]
        public int business_unit_id
        {
            get { return fbusiness_unit_id; }
            set { SetPropertyValue<int>("business_unit_id", ref fbusiness_unit_id, value); }
        }
    }

}
