//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    [Indices(@"member_id;is_active", "member_id;dt_init")]
    public partial class ne_session : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        string fip;
        [Indexed(Name = @"ip")]
        [Size(15)]
        public string ip
        {
            get { return fip; }
            set { SetPropertyValue<string>("ip", ref fip, value); }
        }
        int fmember_id;
        [Indexed(Name = @"member_id")]
        public int member_id
        {
            get { return fmember_id; }
            set { SetPropertyValue<int>("member_id", ref fmember_id, value); }
        }
        bool fis_active;
        public bool is_active
        {
            get { return fis_active; }
            set { SetPropertyValue<bool>("is_active", ref fis_active, value); }
        }
        bool fis_contact;
        public bool is_contact
        {
            get { return fis_contact; }
            set { SetPropertyValue<bool>("is_contact", ref fis_contact, value); }
        }
        DateTime fdt_init;
        public DateTime dt_init
        {
            get { return fdt_init; }
            set { SetPropertyValue<DateTime>("dt_init", ref fdt_init, value); }
        }
        int fres_x;
        public int res_x
        {
            get { return fres_x; }
            set { SetPropertyValue<int>("res_x", ref fres_x, value); }
        }
        int fres_y;
        public int res_y
        {
            get { return fres_y; }
            set { SetPropertyValue<int>("res_y", ref fres_y, value); }
        }
    }

}
