//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    [Indices(@"table;table_id")]
    public partial class partner_skills : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        string ftable;
        [Indexed(Name = @"table")]
        [Size(255)]
        public string table
        {
            get { return ftable; }
            set { SetPropertyValue<string>("table", ref ftable, value); }
        }
        int ftable_id;
        public int table_id
        {
            get { return ftable_id; }
            set { SetPropertyValue<int>("table_id", ref ftable_id, value); }
        }
        string fskill;
        [Size(500)]
        public string skill
        {
            get { return fskill; }
            set { SetPropertyValue<string>("skill", ref fskill, value); }
        }
        int fadded_by;
        public int added_by
        {
            get { return fadded_by; }
            set { SetPropertyValue<int>("added_by", ref fadded_by, value); }
        }
        DateTime fdate_added;
        public DateTime date_added
        {
            get { return fdate_added; }
            set { SetPropertyValue<DateTime>("date_added", ref fdate_added, value); }
        }
    }

}
