//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    [Indices(@"member_id;payperiod_id;type")]
    public partial class payroll_extra_payments : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        char ftype;
        public char type
        {
            get { return ftype; }
            set { SetPropertyValue<char>("type", ref ftype, value); }
        }
        int fpayperiod_id;
        [Indexed(Name = @"payperiod_id")]
        public int payperiod_id
        {
            get { return fpayperiod_id; }
            set { SetPropertyValue<int>("payperiod_id", ref fpayperiod_id, value); }
        }
        uint fmember_id;
        [Indexed(Name = @"member_id")]
        public uint member_id
        {
            get { return fmember_id; }
            set { SetPropertyValue<uint>("member_id", ref fmember_id, value); }
        }
        DateTime frequested_when;
        public DateTime requested_when
        {
            get { return frequested_when; }
            set { SetPropertyValue<DateTime>("requested_when", ref frequested_when, value); }
        }
        uint frequested_by;
        [Indexed(Name = @"requested_by")]
        public uint requested_by
        {
            get { return frequested_by; }
            set { SetPropertyValue<uint>("requested_by", ref frequested_by, value); }
        }
        int fapproved;
        public int approved
        {
            get { return fapproved; }
            set { SetPropertyValue<int>("approved", ref fapproved, value); }
        }
        DateTime fapproved_when;
        public DateTime approved_when
        {
            get { return fapproved_when; }
            set { SetPropertyValue<DateTime>("approved_when", ref fapproved_when, value); }
        }
        uint fapproved_by;
        [Indexed(Name = @"approved_by")]
        public uint approved_by
        {
            get { return fapproved_by; }
            set { SetPropertyValue<uint>("approved_by", ref fapproved_by, value); }
        }
        double famount;
        public double amount
        {
            get { return famount; }
            set { SetPropertyValue<double>("amount", ref famount, value); }
        }
        string fnote;
        [Size(SizeAttribute.Unlimited)]
        public string note
        {
            get { return fnote; }
            set { SetPropertyValue<string>("note", ref fnote, value); }
        }
    }

}
