//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    public partial class poprog_status : XPLiteObject
    {
        int fpoprog_status_id;
        [Key(true)]
        public int poprog_status_id
        {
            get { return fpoprog_status_id; }
            set { SetPropertyValue<int>("poprog_status_id", ref fpoprog_status_id, value); }
        }
        string fstatus_type;
        [Size(60)]
        public string status_type
        {
            get { return fstatus_type; }
            set { SetPropertyValue<string>("status_type", ref fstatus_type, value); }
        }
        [Association(@"poprogstatusReferencespoprog_status")]
        public XPCollection<poprogstatus> poprogstatusCollection { get { return GetCollection<poprogstatus>("poprogstatusCollection"); } }
    }

}
