//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    public partial class quote_process_questions : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        string fquestion;
        [Size(500)]
        public string question
        {
            get { return fquestion; }
            set { SetPropertyValue<string>("question", ref fquestion, value); }
        }
        string fscoring_guidelines;
        [Size(1000)]
        public string scoring_guidelines
        {
            get { return fscoring_guidelines; }
            set { SetPropertyValue<string>("scoring_guidelines", ref fscoring_guidelines, value); }
        }
        string ftype;
        [Size(50)]
        public string type
        {
            get { return ftype; }
            set { SetPropertyValue<string>("type", ref ftype, value); }
        }
        string fstatus;
        [Size(8)]
        public string status
        {
            get { return fstatus; }
            set { SetPropertyValue<string>("status", ref fstatus, value); }
        }
        int fifyes;
        public int ifyes
        {
            get { return fifyes; }
            set { SetPropertyValue<int>("ifyes", ref fifyes, value); }
        }
        int fifno;
        public int ifno
        {
            get { return fifno; }
            set { SetPropertyValue<int>("ifno", ref fifno, value); }
        }
    }

}
