//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    [Indices(@"customer_id;contact_id", "customer_id;address_id", "active_revision;status_id", "business_unit_id;customer_id", "business_unit_id;quoted_by", "customer_id;quoted_by;contact_id;business_unit_id", "customer_id;quoted_by;business_unit_id;division_id;contact_id")]
    public partial class quote_master : XPLiteObject
    {
        int factive_revision;
        [Indexed(Name = @"active_revision")]
        public int active_revision
        {
            get { return factive_revision; }
            set { SetPropertyValue<int>("active_revision", ref factive_revision, value); }
        }
        int fstatus_id;
        [Indexed(Name = @"status_id")]
        public int status_id
        {
            get { return fstatus_id; }
            set { SetPropertyValue<int>("status_id", ref fstatus_id, value); }
        }
        int fprev_status_id;
        [Indexed(Name = @"prev_status_id")]
        public int prev_status_id
        {
            get { return fprev_status_id; }
            set { SetPropertyValue<int>("prev_status_id", ref fprev_status_id, value); }
        }
        uint fcustomer_id;
        [Indexed(Name = @"Customer_ID")]
        public uint customer_id
        {
            get { return fcustomer_id; }
            set { SetPropertyValue<uint>("customer_id", ref fcustomer_id, value); }
        }
        DateTime fopen_date;
        [Indexed(Name = @"open_date")]
        public DateTime open_date
        {
            get { return fopen_date; }
            set { SetPropertyValue<DateTime>("open_date", ref fopen_date, value); }
        }
        DateTime fdate_due;
        [Indexed(Name = @"date_due")]
        public DateTime date_due
        {
            get { return fdate_due; }
            set { SetPropertyValue<DateTime>("date_due", ref fdate_due, value); }
        }
        DateTime fcompletion_date;
        [Indexed(Name = @"completion_date")]
        public DateTime completion_date
        {
            get { return fcompletion_date; }
            set { SetPropertyValue<DateTime>("completion_date", ref fcompletion_date, value); }
        }
        string fjob_description;
        [Indexed(Name = @"job_description")]
        [Size(SizeAttribute.Unlimited)]
        public string job_description
        {
            get { return fjob_description; }
            set { SetPropertyValue<string>("job_description", ref fjob_description, value); }
        }
        string fcust_spec_doc;
        [Size(150)]
        public string cust_spec_doc
        {
            get { return fcust_spec_doc; }
            set { SetPropertyValue<string>("cust_spec_doc", ref fcust_spec_doc, value); }
        }
        uint fquoted_by;
        [Indexed(Name = @"quoted_by")]
        public uint quoted_by
        {
            get { return fquoted_by; }
            set { SetPropertyValue<uint>("quoted_by", ref fquoted_by, value); }
        }
        int fquoter_locked;
        public int quoter_locked
        {
            get { return fquoter_locked; }
            set { SetPropertyValue<int>("quoter_locked", ref fquoter_locked, value); }
        }
        int fcompany_id;
        public int company_id
        {
            get { return fcompany_id; }
            set { SetPropertyValue<int>("company_id", ref fcompany_id, value); }
        }
        uint fdivision_id;
        public uint division_id
        {
            get { return fdivision_id; }
            set { SetPropertyValue<uint>("division_id", ref fdivision_id, value); }
        }
        uint fkilled_by;
        public uint killed_by
        {
            get { return fkilled_by; }
            set { SetPropertyValue<uint>("killed_by", ref fkilled_by, value); }
        }
        int fcompetitor_id;
        public int competitor_id
        {
            get { return fcompetitor_id; }
            set { SetPropertyValue<int>("competitor_id", ref fcompetitor_id, value); }
        }
        int fcontact_id;
        [Indexed(Name = @"Contact_ID")]
        [Persistent(@"Contact_ID")]
        public int contact_id
        {
            get { return fcontact_id; }
            set { SetPropertyValue<int>("contact_id", ref fcontact_id, value); }
        }
        int finclude_title;
        public int include_title
        {
            get { return finclude_title; }
            set { SetPropertyValue<int>("include_title", ref finclude_title, value); }
        }
        DateTime flast_print_date;
        [Indexed(Name = @"last_print_date")]
        public DateTime last_print_date
        {
            get { return flast_print_date; }
            set { SetPropertyValue<DateTime>("last_print_date", ref flast_print_date, value); }
        }
        DateTime flast_fax_date;
        public DateTime last_fax_date
        {
            get { return flast_fax_date; }
            set { SetPropertyValue<DateTime>("last_fax_date", ref flast_fax_date, value); }
        }
        DateTime fverified_date;
        public DateTime verified_date
        {
            get { return fverified_date; }
            set { SetPropertyValue<DateTime>("verified_date", ref fverified_date, value); }
        }
        decimal fquoted_price;
        [Indexed(Name = @"quoted_price")]
        public decimal quoted_price
        {
            get { return fquoted_price; }
            set { SetPropertyValue<decimal>("quoted_price", ref fquoted_price, value); }
        }
        decimal fprice_to;
        public decimal price_to
        {
            get { return fprice_to; }
            set { SetPropertyValue<decimal>("price_to", ref fprice_to, value); }
        }
        decimal ftake_off_price;
        public decimal take_off_price
        {
            get { return ftake_off_price; }
            set { SetPropertyValue<decimal>("take_off_price", ref ftake_off_price, value); }
        }
        string fcustom_term;
        [Size(500)]
        public string custom_term
        {
            get { return fcustom_term; }
            set { SetPropertyValue<string>("custom_term", ref fcustom_term, value); }
        }
        decimal ftm_pricing;
        public decimal tm_pricing
        {
            get { return ftm_pricing; }
            set { SetPropertyValue<decimal>("tm_pricing", ref ftm_pricing, value); }
        }
        int fnet_due;
        public int net_due
        {
            get { return fnet_due; }
            set { SetPropertyValue<int>("net_due", ref fnet_due, value); }
        }
        int fpercentage_down;
        public int percentage_down
        {
            get { return fpercentage_down; }
            set { SetPropertyValue<int>("percentage_down", ref fpercentage_down, value); }
        }
        int fus_currency;
        [Indexed(Name = @"us_currency")]
        public int us_currency
        {
            get { return fus_currency; }
            set { SetPropertyValue<int>("us_currency", ref fus_currency, value); }
        }
        int finflation_term;
        public int inflation_term
        {
            get { return finflation_term; }
            set { SetPropertyValue<int>("inflation_term", ref finflation_term, value); }
        }
        int fpricetype_id;
        [Indexed(Name = @"pricetype_id")]
        public int pricetype_id
        {
            get { return fpricetype_id; }
            set { SetPropertyValue<int>("pricetype_id", ref fpricetype_id, value); }
        }
        string fpo;
        [Size(45)]
        public string po
        {
            get { return fpo; }
            set { SetPropertyValue<string>("po", ref fpo, value); }
        }
        int fwo;
        [Indexed(Name = @"wo")]
        public int wo
        {
            get { return fwo; }
            set { SetPropertyValue<int>("wo", ref fwo, value); }
        }
        uint fduped_from_id;
        public uint duped_from_id
        {
            get { return fduped_from_id; }
            set { SetPropertyValue<uint>("duped_from_id", ref fduped_from_id, value); }
        }
        int fduped_from_rev;
        public int duped_from_rev
        {
            get { return fduped_from_rev; }
            set { SetPropertyValue<int>("duped_from_rev", ref fduped_from_rev, value); }
        }
        string fupdated_by_page;
        public string updated_by_page
        {
            get { return fupdated_by_page; }
            set { SetPropertyValue<string>("updated_by_page", ref fupdated_by_page, value); }
        }
        int fsuccess_percent;
        public int success_percent
        {
            get { return fsuccess_percent; }
            set { SetPropertyValue<int>("success_percent", ref fsuccess_percent, value); }
        }
        byte fquote_master_apply_discount;
        public byte quote_master_apply_discount
        {
            get { return fquote_master_apply_discount; }
            set { SetPropertyValue<byte>("quote_master_apply_discount", ref fquote_master_apply_discount, value); }
        }
        int faddress_id;
        [Indexed(Name = @"address_id")]
        public int address_id
        {
            get { return faddress_id; }
            set { SetPropertyValue<int>("address_id", ref faddress_id, value); }
        }
        string fwhy_lose;
        [Size(1000)]
        public string why_lose
        {
            get { return fwhy_lose; }
            set { SetPropertyValue<string>("why_lose", ref fwhy_lose, value); }
        }
        string fwho_competitor;
        [Size(1000)]
        public string who_competitor
        {
            get { return fwho_competitor; }
            set { SetPropertyValue<string>("who_competitor", ref fwho_competitor, value); }
        }
        string fwhat_price;
        [Size(1000)]
        public string what_price
        {
            get { return fwhat_price; }
            set { SetPropertyValue<string>("what_price", ref fwhat_price, value); }
        }
        string fcust_reason_for_close;
        [Size(1000)]
        public string cust_reason_for_close
        {
            get { return fcust_reason_for_close; }
            set { SetPropertyValue<string>("cust_reason_for_close", ref fcust_reason_for_close, value); }
        }
        int fpct_chance;
        [Indexed(Name = @"pct_chance")]
        public int pct_chance
        {
            get { return fpct_chance; }
            set { SetPropertyValue<int>("pct_chance", ref fpct_chance, value); }
        }
        int fpct_chance_reason;
        [Indexed(Name = @"pct_chance_reason")]
        public int pct_chance_reason
        {
            get { return fpct_chance_reason; }
            set { SetPropertyValue<int>("pct_chance_reason", ref fpct_chance_reason, value); }
        }
        string fpct_chance_note;
        [Size(SizeAttribute.Unlimited)]
        public string pct_chance_note
        {
            get { return fpct_chance_note; }
            set { SetPropertyValue<string>("pct_chance_note", ref fpct_chance_note, value); }
        }
        double fhours_spent;
        [Indexed(Name = @"hours_spent")]
        public double hours_spent
        {
            get { return fhours_spent; }
            set { SetPropertyValue<double>("hours_spent", ref fhours_spent, value); }
        }
        bool fuse_current_cost;
        public bool use_current_cost
        {
            get { return fuse_current_cost; }
            set { SetPropertyValue<bool>("use_current_cost", ref fuse_current_cost, value); }
        }
        double fmargin;
        public double margin
        {
            get { return fmargin; }
            set { SetPropertyValue<double>("margin", ref fmargin, value); }
        }
        double fexpected_value;
        public double expected_value
        {
            get { return fexpected_value; }
            set { SetPropertyValue<double>("expected_value", ref fexpected_value, value); }
        }
        bool ffollow_up;
        public bool follow_up
        {
            get { return ffollow_up; }
            set { SetPropertyValue<bool>("follow_up", ref ffollow_up, value); }
        }
        int fallowed_to_quote;
        [Indexed(Name = @"allowed_to_quote")]
        public int allowed_to_quote
        {
            get { return fallowed_to_quote; }
            set { SetPropertyValue<int>("allowed_to_quote", ref fallowed_to_quote, value); }
        }
        int fallowed_to_quote_2;
        [Indexed(Name = @"allowed_to_quote_2")]
        public int allowed_to_quote_2
        {
            get { return fallowed_to_quote_2; }
            set { SetPropertyValue<int>("allowed_to_quote_2", ref fallowed_to_quote_2, value); }
        }
        string fkilled_at_stage;
        [Indexed(Name = @"killed_at_stage")]
        [Size(30)]
        public string killed_at_stage
        {
            get { return fkilled_at_stage; }
            set { SetPropertyValue<string>("killed_at_stage", ref fkilled_at_stage, value); }
        }
        DateTime fkilled_date;
        public DateTime killed_date
        {
            get { return fkilled_date; }
            set { SetPropertyValue<DateTime>("killed_date", ref fkilled_date, value); }
        }
        string fwhy_killed;
        [Size(767)]
        public string why_killed
        {
            get { return fwhy_killed; }
            set { SetPropertyValue<string>("why_killed", ref fwhy_killed, value); }
        }
        int fcurrency;
        public int currency
        {
            get { return fcurrency; }
            set { SetPropertyValue<int>("currency", ref fcurrency, value); }
        }
        string fwhy_revised;
        [Size(1000)]
        public string why_revised
        {
            get { return fwhy_revised; }
            set { SetPropertyValue<string>("why_revised", ref fwhy_revised, value); }
        }
        int fbusiness_unit_id;
        [Indexed(Name = @"idx_quote_master_business_unit_id")]
        public int business_unit_id
        {
            get { return fbusiness_unit_id; }
            set { SetPropertyValue<int>("business_unit_id", ref fbusiness_unit_id, value); }
        }
        DateTime fexp_podate;
        public DateTime exp_podate
        {
            get { return fexp_podate; }
            set { SetPropertyValue<DateTime>("exp_podate", ref fexp_podate, value); }
        }
        bool fparallel_bid;
        public bool parallel_bid
        {
            get { return fparallel_bid; }
            set { SetPropertyValue<bool>("parallel_bid", ref fparallel_bid, value); }
        }
        DateTime flast_saved;
        public DateTime last_saved
        {
            get { return flast_saved; }
            set { SetPropertyValue<DateTime>("last_saved", ref flast_saved, value); }
        }
        DateTime fdate_expected_start;
        public DateTime date_expected_start
        {
            get { return fdate_expected_start; }
            set { SetPropertyValue<DateTime>("date_expected_start", ref fdate_expected_start, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("quote_id")]
            public uint quote_id;
            [Persistent("revision")]
            public int revision;
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
        int frevenue_line_id;
        [ColumnDefaultValue(0)]
        public int revenue_line_id
        {
            get { return frevenue_line_id; }
            set { SetPropertyValue<int>("revenue_line_id", ref frevenue_line_id, value); }
        }
        bool fis_tm;
        [ColumnDefaultValue(false)]
        public bool is_tm
        {
            get { return fis_tm; }
            set { SetPropertyValue<bool>("is_tm", ref fis_tm, value); }
        }
        int fperiod_valid;
        [ColumnDefaultValue(30)]
        public int period_valid
        {
            get { return fperiod_valid; }
            set { SetPropertyValue<int>("period_valid", ref fperiod_valid, value); }
        }
    }

}
