//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    [Indices(@"tax_name;tax_bv_s_tax_no")]
    public partial class tax : XPLiteObject
    {
        int ftax_id;
        [Key(true)]
        public int tax_id
        {
            get { return ftax_id; }
            set { SetPropertyValue<int>("tax_id", ref ftax_id, value); }
        }
        string ftax_name;
        [Indexed(Name = @"tax_name")]
        public string tax_name
        {
            get { return ftax_name; }
            set { SetPropertyValue<string>("tax_name", ref ftax_name, value); }
        }
        decimal ftax_percentage;
        public decimal tax_percentage
        {
            get { return ftax_percentage; }
            set { SetPropertyValue<decimal>("tax_percentage", ref ftax_percentage, value); }
        }
        string ftax_description;
        [Size(SizeAttribute.Unlimited)]
        public string tax_description
        {
            get { return ftax_description; }
            set { SetPropertyValue<string>("tax_description", ref ftax_description, value); }
        }
        string ftax_glaccount;
        [Size(SizeAttribute.Unlimited)]
        public string tax_glaccount
        {
            get { return ftax_glaccount; }
            set { SetPropertyValue<string>("tax_glaccount", ref ftax_glaccount, value); }
        }
        int ftax_bv_s_tax_no;
        [Indexed(Name = @"tax_bv_s_tax_no")]
        public int tax_bv_s_tax_no
        {
            get { return ftax_bv_s_tax_no; }
            set { SetPropertyValue<int>("tax_bv_s_tax_no", ref ftax_bv_s_tax_no, value); }
        }
        bool fis_active;
        public bool is_active
        {
            get { return fis_active; }
            set { SetPropertyValue<bool>("is_active", ref fis_active, value); }
        }
        int fshould_be;
        public int should_be
        {
            get { return fshould_be; }
            set { SetPropertyValue<int>("should_be", ref fshould_be, value); }
        }
    }

}
