//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    [Indices(@"tax_entity_group_id;tax_entity_id")]
    public partial class tax_entity_group_link : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        tax_entity_group ftax_entity_group_id;
        [Indexed(Name = @"tax_entity_group_id")]
        [Association(@"tax_entity_group_linkReferencestax_entity_group")]
        public tax_entity_group tax_entity_group_id
        {
            get { return ftax_entity_group_id; }
            set { SetPropertyValue<tax_entity_group>("tax_entity_group_id", ref ftax_entity_group_id, value); }
        }
        tax_entity ftax_entity_id;
        [Indexed(Name = @"tax_entity_id")]
        [Association(@"tax_entity_group_linkReferencestax_entity")]
        public tax_entity tax_entity_id
        {
            get { return ftax_entity_id; }
            set { SetPropertyValue<tax_entity>("tax_entity_id", ref ftax_entity_id, value); }
        }
    }

}
