//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    public partial class ticketpriority : XPLiteObject
    {
        int fticketpriority_id;
        [Key(true)]
        public int ticketpriority_id
        {
            get { return fticketpriority_id; }
            set { SetPropertyValue<int>("ticketpriority_id", ref fticketpriority_id, value); }
        }
        string fticketpriority_name;
        [Size(50)]
        public string ticketpriority_name
        {
            get { return fticketpriority_name; }
            set { SetPropertyValue<string>("ticketpriority_name", ref fticketpriority_name, value); }
        }
        [Association(@"ticketheaderReferencesticketpriority")]
        public XPCollection<ticketheader> ticketheaders { get { return GetCollection<ticketheader>("ticketheaders"); } }
    }

}
