//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    public partial class ticket_memberview : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        ticketheader fticket_id;
        [Association(@"ticket_memberviewReferencesticketheader")]
        public ticketheader ticket_id
        {
            get { return fticket_id; }
            set { SetPropertyValue<ticketheader>("ticket_id", ref fticket_id, value); }
        }
        member fmember_id;
        [Association(@"ticket_memberviewReferencesmember")]
        public member member_id
        {
            get { return fmember_id; }
            set { SetPropertyValue<member>("member_id", ref fmember_id, value); }
        }
    }

}
