//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    public partial class video : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        int fcategory_id;
        [Indexed(Name = @"key_category")]
        public int category_id
        {
            get { return fcategory_id; }
            set { SetPropertyValue<int>("category_id", ref fcategory_id, value); }
        }
        string fname;
        [Indexed(Name = @"key_name")]
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>("name", ref fname, value); }
        }
        string fdescription;
        [Size(SizeAttribute.Unlimited)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        int ffile_id;
        public int file_id
        {
            get { return ffile_id; }
            set { SetPropertyValue<int>("file_id", ref ffile_id, value); }
        }
        bool fis_selected;
        public bool is_selected
        {
            get { return fis_selected; }
            set { SetPropertyValue<bool>("is_selected", ref fis_selected, value); }
        }
    }

}
