//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    public partial class who_to_ask : XPLiteObject
    {
        int fwho_to_ask_id;
        [Key(true)]
        public int who_to_ask_id
        {
            get { return fwho_to_ask_id; }
            set { SetPropertyValue<int>("who_to_ask_id", ref fwho_to_ask_id, value); }
        }
        int fwho_to_ask_memberid;
        public int who_to_ask_memberid
        {
            get { return fwho_to_ask_memberid; }
            set { SetPropertyValue<int>("who_to_ask_memberid", ref fwho_to_ask_memberid, value); }
        }
        int fwho_to_ask_membertype;
        public int who_to_ask_membertype
        {
            get { return fwho_to_ask_membertype; }
            set { SetPropertyValue<int>("who_to_ask_membertype", ref fwho_to_ask_membertype, value); }
        }
        string fwho_to_ask_question;
        [Size(255)]
        public string who_to_ask_question
        {
            get { return fwho_to_ask_question; }
            set { SetPropertyValue<string>("who_to_ask_question", ref fwho_to_ask_question, value); }
        }
    }

}
