//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    [Indices(@"woprog_id;P_order")]
    public partial class woprog_tasks : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        int fwoprog_id;
        [Indexed(Name = @"woprog_id")]
        public int woprog_id
        {
            get { return fwoprog_id; }
            set { SetPropertyValue<int>("woprog_id", ref fwoprog_id, value); }
        }
        string ftask;
        [Size(SizeAttribute.Unlimited)]
        public string task
        {
            get { return ftask; }
            set { SetPropertyValue<string>("task", ref ftask, value); }
        }
        sbyte fcomplete;
        [Indexed(Name = @"complete")]
        public sbyte complete
        {
            get { return fcomplete; }
            set { SetPropertyValue<sbyte>("complete", ref fcomplete, value); }
        }
        int fP_order;
        [Indexed(Name = @"order")]
        [Persistent(@"_order")]
        public int P_order
        {
            get { return fP_order; }
            set { SetPropertyValue<int>("P_order", ref fP_order, value); }
        }
        bool fis_insepection;
        public bool is_insepection
        {
            get { return fis_insepection; }
            set { SetPropertyValue<bool>("is_insepection", ref fis_insepection, value); }
        }
        [Association(@"membertimeReferenceswoprog_tasks")]
        public XPCollection<membertime> membertimes { get { return GetCollection<membertime>("membertimes"); } }
    }

}
