//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ne_xpo.cs
{

    public partial class woprogcomment : XPLiteObject
    {
        uint fwoprogcomment_id;
        [Key]
        [Persistent(@"WOProgComment_ID")]
        public uint woprogcomment_id
        {
            get { return fwoprogcomment_id; }
            set { SetPropertyValue<uint>("woprogcomment_id", ref fwoprogcomment_id, value); }
        }
        uint fwoprogcomment_woprog_id;
        [Indexed(Name = @"WOProgComment_WOProg_ID")]
        [Persistent(@"WOProgComment_WOProg_ID")]
        public uint woprogcomment_woprog_id
        {
            get { return fwoprogcomment_woprog_id; }
            set { SetPropertyValue<uint>("woprogcomment_woprog_id", ref fwoprogcomment_woprog_id, value); }
        }
        uint fwoprogcomment_member_id;
        [Indexed(Name = @"WOProgComment_Member_ID")]
        [Persistent(@"WOProgComment_Member_ID")]
        public uint woprogcomment_member_id
        {
            get { return fwoprogcomment_member_id; }
            set { SetPropertyValue<uint>("woprogcomment_member_id", ref fwoprogcomment_member_id, value); }
        }
        string fwoprogcomment_text;
        [Size(SizeAttribute.Unlimited)]
        public string woprogcomment_text
        {
            get { return fwoprogcomment_text; }
            set { SetPropertyValue<string>("woprogcomment_text", ref fwoprogcomment_text, value); }
        }
        long fwoprogcomment_x;
        [Persistent(@"WOProgComment_X")]
        public long woprogcomment_x
        {
            get { return fwoprogcomment_x; }
            set { SetPropertyValue<long>("woprogcomment_x", ref fwoprogcomment_x, value); }
        }
        long fwoprogcomment_y;
        [Persistent(@"WOProgComment_Y")]
        public long woprogcomment_y
        {
            get { return fwoprogcomment_y; }
            set { SetPropertyValue<long>("woprogcomment_y", ref fwoprogcomment_y, value); }
        }
        DateTime fwoprogcomment_datetime;
        [Persistent(@"WOProgComment_DateTime")]
        public DateTime woprogcomment_datetime
        {
            get { return fwoprogcomment_datetime; }
            set { SetPropertyValue<DateTime>("woprogcomment_datetime", ref fwoprogcomment_datetime, value); }
        }
    }

}
